/*
 * This file is generated by jOOQ.
 */
package com.RodiejaContable.database.jooq.tables.records;


import com.RodiejaContable.database.jooq.tables.Generaciones;

import java.math.BigDecimal;
import java.time.LocalDateTime;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class GeneracionesRecord extends UpdatableRecordImpl<GeneracionesRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>sistema_vehicular.generaciones.id</code>.
     */
    public GeneracionesRecord setId(Integer value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>sistema_vehicular.generaciones.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>sistema_vehicular.generaciones.modelo_id</code>.
     */
    public GeneracionesRecord setModeloId(Integer value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>sistema_vehicular.generaciones.modelo_id</code>.
     */
    public Integer getModeloId() {
        return (Integer) get(1);
    }

    /**
     * Setter for <code>sistema_vehicular.generaciones.nombre</code>.
     */
    public GeneracionesRecord setNombre(String value) {
        set(2, value);
        return this;
    }

    /**
     * Getter for <code>sistema_vehicular.generaciones.nombre</code>.
     */
    public String getNombre() {
        return (String) get(2);
    }

    /**
     * Setter for <code>sistema_vehicular.generaciones.descripcion</code>.
     */
    public GeneracionesRecord setDescripcion(String value) {
        set(3, value);
        return this;
    }

    /**
     * Getter for <code>sistema_vehicular.generaciones.descripcion</code>.
     */
    public String getDescripcion() {
        return (String) get(3);
    }

    /**
     * Setter for <code>sistema_vehicular.generaciones.anio_inicio</code>.
     */
    public GeneracionesRecord setAnioInicio(Integer value) {
        set(4, value);
        return this;
    }

    /**
     * Getter for <code>sistema_vehicular.generaciones.anio_inicio</code>.
     */
    public Integer getAnioInicio() {
        return (Integer) get(4);
    }

    /**
     * Setter for <code>sistema_vehicular.generaciones.anio_fin</code>.
     */
    public GeneracionesRecord setAnioFin(Integer value) {
        set(5, value);
        return this;
    }

    /**
     * Getter for <code>sistema_vehicular.generaciones.anio_fin</code>.
     */
    public Integer getAnioFin() {
        return (Integer) get(5);
    }

    /**
     * Setter for <code>sistema_vehicular.generaciones.total_inversion</code>.
     */
    public GeneracionesRecord setTotalInversion(BigDecimal value) {
        set(6, value);
        return this;
    }

    /**
     * Getter for <code>sistema_vehicular.generaciones.total_inversion</code>.
     */
    public BigDecimal getTotalInversion() {
        return (BigDecimal) get(6);
    }

    /**
     * Setter for <code>sistema_vehicular.generaciones.total_ingresos</code>.
     */
    public GeneracionesRecord setTotalIngresos(BigDecimal value) {
        set(7, value);
        return this;
    }

    /**
     * Getter for <code>sistema_vehicular.generaciones.total_ingresos</code>.
     */
    public BigDecimal getTotalIngresos() {
        return (BigDecimal) get(7);
    }

    /**
     * Setter for <code>sistema_vehicular.generaciones.total_egresos</code>.
     */
    public GeneracionesRecord setTotalEgresos(BigDecimal value) {
        set(8, value);
        return this;
    }

    /**
     * Getter for <code>sistema_vehicular.generaciones.total_egresos</code>.
     */
    public BigDecimal getTotalEgresos() {
        return (BigDecimal) get(8);
    }

    /**
     * Setter for <code>sistema_vehicular.generaciones.balance_neto</code>.
     */
    public GeneracionesRecord setBalanceNeto(BigDecimal value) {
        set(9, value);
        return this;
    }

    /**
     * Getter for <code>sistema_vehicular.generaciones.balance_neto</code>.
     */
    public BigDecimal getBalanceNeto() {
        return (BigDecimal) get(9);
    }

    /**
     * Setter for <code>sistema_vehicular.generaciones.activo</code>.
     */
    public GeneracionesRecord setActivo(Byte value) {
        set(10, value);
        return this;
    }

    /**
     * Getter for <code>sistema_vehicular.generaciones.activo</code>.
     */
    public Byte getActivo() {
        return (Byte) get(10);
    }

    /**
     * Setter for <code>sistema_vehicular.generaciones.fecha_creacion</code>.
     */
    public GeneracionesRecord setFechaCreacion(LocalDateTime value) {
        set(11, value);
        return this;
    }

    /**
     * Getter for <code>sistema_vehicular.generaciones.fecha_creacion</code>.
     */
    public LocalDateTime getFechaCreacion() {
        return (LocalDateTime) get(11);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached GeneracionesRecord
     */
    public GeneracionesRecord() {
        super(Generaciones.GENERACIONES);
    }

    /**
     * Create a detached, initialised GeneracionesRecord
     */
    public GeneracionesRecord(Integer id, Integer modeloId, String nombre, String descripcion, Integer anioInicio, Integer anioFin, BigDecimal totalInversion, BigDecimal totalIngresos, BigDecimal totalEgresos, BigDecimal balanceNeto, Byte activo, LocalDateTime fechaCreacion) {
        super(Generaciones.GENERACIONES);

        setId(id);
        setModeloId(modeloId);
        setNombre(nombre);
        setDescripcion(descripcion);
        setAnioInicio(anioInicio);
        setAnioFin(anioFin);
        setTotalInversion(totalInversion);
        setTotalIngresos(totalIngresos);
        setTotalEgresos(totalEgresos);
        setBalanceNeto(balanceNeto);
        setActivo(activo);
        setFechaCreacion(fechaCreacion);
        resetChangedOnNotNull();
    }

    /**
     * Create a detached, initialised GeneracionesRecord
     */
    public GeneracionesRecord(com.RodiejaContable.database.jooq.tables.pojos.Generaciones value) {
        super(Generaciones.GENERACIONES);

        if (value != null) {
            setId(value.getId());
            setModeloId(value.getModeloId());
            setNombre(value.getNombre());
            setDescripcion(value.getDescripcion());
            setAnioInicio(value.getAnioInicio());
            setAnioFin(value.getAnioFin());
            setTotalInversion(value.getTotalInversion());
            setTotalIngresos(value.getTotalIngresos());
            setTotalEgresos(value.getTotalEgresos());
            setBalanceNeto(value.getBalanceNeto());
            setActivo(value.getActivo());
            setFechaCreacion(value.getFechaCreacion());
            resetChangedOnNotNull();
        }
    }
}
