/*
 * This file is generated by jOOQ.
 */
package com.RodiejaContable.database.jooq.tables.records;


import com.RodiejaContable.database.jooq.enums.HistorialVehiculosAccion;
import com.RodiejaContable.database.jooq.tables.HistorialVehiculos;

import java.time.LocalDateTime;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class HistorialVehiculosRecord extends UpdatableRecordImpl<HistorialVehiculosRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>sistema_vehicular.historial_vehiculos.id</code>.
     */
    public HistorialVehiculosRecord setId(Integer value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>sistema_vehicular.historial_vehiculos.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for
     * <code>sistema_vehicular.historial_vehiculos.vehiculo_id</code>.
     */
    public HistorialVehiculosRecord setVehiculoId(Integer value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for
     * <code>sistema_vehicular.historial_vehiculos.vehiculo_id</code>.
     */
    public Integer getVehiculoId() {
        return (Integer) get(1);
    }

    /**
     * Setter for <code>sistema_vehicular.historial_vehiculos.accion</code>.
     */
    public HistorialVehiculosRecord setAccion(HistorialVehiculosAccion value) {
        set(2, value);
        return this;
    }

    /**
     * Getter for <code>sistema_vehicular.historial_vehiculos.accion</code>.
     */
    public HistorialVehiculosAccion getAccion() {
        return (HistorialVehiculosAccion) get(2);
    }

    /**
     * Setter for
     * <code>sistema_vehicular.historial_vehiculos.campo_modificado</code>.
     */
    public HistorialVehiculosRecord setCampoModificado(String value) {
        set(3, value);
        return this;
    }

    /**
     * Getter for
     * <code>sistema_vehicular.historial_vehiculos.campo_modificado</code>.
     */
    public String getCampoModificado() {
        return (String) get(3);
    }

    /**
     * Setter for
     * <code>sistema_vehicular.historial_vehiculos.valor_anterior</code>.
     */
    public HistorialVehiculosRecord setValorAnterior(String value) {
        set(4, value);
        return this;
    }

    /**
     * Getter for
     * <code>sistema_vehicular.historial_vehiculos.valor_anterior</code>.
     */
    public String getValorAnterior() {
        return (String) get(4);
    }

    /**
     * Setter for
     * <code>sistema_vehicular.historial_vehiculos.valor_nuevo</code>.
     */
    public HistorialVehiculosRecord setValorNuevo(String value) {
        set(5, value);
        return this;
    }

    /**
     * Getter for
     * <code>sistema_vehicular.historial_vehiculos.valor_nuevo</code>.
     */
    public String getValorNuevo() {
        return (String) get(5);
    }

    /**
     * Setter for <code>sistema_vehicular.historial_vehiculos.usuario</code>.
     */
    public HistorialVehiculosRecord setUsuario(String value) {
        set(6, value);
        return this;
    }

    /**
     * Getter for <code>sistema_vehicular.historial_vehiculos.usuario</code>.
     */
    public String getUsuario() {
        return (String) get(6);
    }

    /**
     * Setter for
     * <code>sistema_vehicular.historial_vehiculos.fecha_cambio</code>.
     */
    public HistorialVehiculosRecord setFechaCambio(LocalDateTime value) {
        set(7, value);
        return this;
    }

    /**
     * Getter for
     * <code>sistema_vehicular.historial_vehiculos.fecha_cambio</code>.
     */
    public LocalDateTime getFechaCambio() {
        return (LocalDateTime) get(7);
    }

    /**
     * Setter for <code>sistema_vehicular.historial_vehiculos.ip_usuario</code>.
     */
    public HistorialVehiculosRecord setIpUsuario(String value) {
        set(8, value);
        return this;
    }

    /**
     * Getter for <code>sistema_vehicular.historial_vehiculos.ip_usuario</code>.
     */
    public String getIpUsuario() {
        return (String) get(8);
    }

    /**
     * Setter for
     * <code>sistema_vehicular.historial_vehiculos.observaciones</code>.
     */
    public HistorialVehiculosRecord setObservaciones(String value) {
        set(9, value);
        return this;
    }

    /**
     * Getter for
     * <code>sistema_vehicular.historial_vehiculos.observaciones</code>.
     */
    public String getObservaciones() {
        return (String) get(9);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached HistorialVehiculosRecord
     */
    public HistorialVehiculosRecord() {
        super(HistorialVehiculos.HISTORIAL_VEHICULOS);
    }

    /**
     * Create a detached, initialised HistorialVehiculosRecord
     */
    public HistorialVehiculosRecord(Integer id, Integer vehiculoId, HistorialVehiculosAccion accion, String campoModificado, String valorAnterior, String valorNuevo, String usuario, LocalDateTime fechaCambio, String ipUsuario, String observaciones) {
        super(HistorialVehiculos.HISTORIAL_VEHICULOS);

        setId(id);
        setVehiculoId(vehiculoId);
        setAccion(accion);
        setCampoModificado(campoModificado);
        setValorAnterior(valorAnterior);
        setValorNuevo(valorNuevo);
        setUsuario(usuario);
        setFechaCambio(fechaCambio);
        setIpUsuario(ipUsuario);
        setObservaciones(observaciones);
        resetChangedOnNotNull();
    }

    /**
     * Create a detached, initialised HistorialVehiculosRecord
     */
    public HistorialVehiculosRecord(com.RodiejaContable.database.jooq.tables.pojos.HistorialVehiculos value) {
        super(HistorialVehiculos.HISTORIAL_VEHICULOS);

        if (value != null) {
            setId(value.getId());
            setVehiculoId(value.getVehiculoId());
            setAccion(value.getAccion());
            setCampoModificado(value.getCampoModificado());
            setValorAnterior(value.getValorAnterior());
            setValorNuevo(value.getValorNuevo());
            setUsuario(value.getUsuario());
            setFechaCambio(value.getFechaCambio());
            setIpUsuario(value.getIpUsuario());
            setObservaciones(value.getObservaciones());
            resetChangedOnNotNull();
        }
    }
}
