/*
 * This file is generated by jOOQ.
 */
package com.RodiejaContable.database.jooq.tables.records;


import com.RodiejaContable.database.jooq.enums.HistorialRepuestosAccion;
import com.RodiejaContable.database.jooq.tables.HistorialRepuestos;

import java.time.LocalDateTime;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class HistorialRepuestosRecord extends UpdatableRecordImpl<HistorialRepuestosRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>sistema_vehicular.historial_repuestos.id</code>.
     */
    public HistorialRepuestosRecord setId(Integer value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>sistema_vehicular.historial_repuestos.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for
     * <code>sistema_vehicular.historial_repuestos.repuesto_id</code>.
     */
    public HistorialRepuestosRecord setRepuestoId(Integer value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for
     * <code>sistema_vehicular.historial_repuestos.repuesto_id</code>.
     */
    public Integer getRepuestoId() {
        return (Integer) get(1);
    }

    /**
     * Setter for <code>sistema_vehicular.historial_repuestos.accion</code>.
     */
    public HistorialRepuestosRecord setAccion(HistorialRepuestosAccion value) {
        set(2, value);
        return this;
    }

    /**
     * Getter for <code>sistema_vehicular.historial_repuestos.accion</code>.
     */
    public HistorialRepuestosAccion getAccion() {
        return (HistorialRepuestosAccion) get(2);
    }

    /**
     * Setter for
     * <code>sistema_vehicular.historial_repuestos.campo_modificado</code>.
     */
    public HistorialRepuestosRecord setCampoModificado(String value) {
        set(3, value);
        return this;
    }

    /**
     * Getter for
     * <code>sistema_vehicular.historial_repuestos.campo_modificado</code>.
     */
    public String getCampoModificado() {
        return (String) get(3);
    }

    /**
     * Setter for
     * <code>sistema_vehicular.historial_repuestos.valor_anterior</code>.
     */
    public HistorialRepuestosRecord setValorAnterior(String value) {
        set(4, value);
        return this;
    }

    /**
     * Getter for
     * <code>sistema_vehicular.historial_repuestos.valor_anterior</code>.
     */
    public String getValorAnterior() {
        return (String) get(4);
    }

    /**
     * Setter for
     * <code>sistema_vehicular.historial_repuestos.valor_nuevo</code>.
     */
    public HistorialRepuestosRecord setValorNuevo(String value) {
        set(5, value);
        return this;
    }

    /**
     * Getter for
     * <code>sistema_vehicular.historial_repuestos.valor_nuevo</code>.
     */
    public String getValorNuevo() {
        return (String) get(5);
    }

    /**
     * Setter for <code>sistema_vehicular.historial_repuestos.usuario</code>.
     */
    public HistorialRepuestosRecord setUsuario(String value) {
        set(6, value);
        return this;
    }

    /**
     * Getter for <code>sistema_vehicular.historial_repuestos.usuario</code>.
     */
    public String getUsuario() {
        return (String) get(6);
    }

    /**
     * Setter for
     * <code>sistema_vehicular.historial_repuestos.fecha_cambio</code>.
     */
    public HistorialRepuestosRecord setFechaCambio(LocalDateTime value) {
        set(7, value);
        return this;
    }

    /**
     * Getter for
     * <code>sistema_vehicular.historial_repuestos.fecha_cambio</code>.
     */
    public LocalDateTime getFechaCambio() {
        return (LocalDateTime) get(7);
    }

    /**
     * Setter for <code>sistema_vehicular.historial_repuestos.ip_usuario</code>.
     */
    public HistorialRepuestosRecord setIpUsuario(String value) {
        set(8, value);
        return this;
    }

    /**
     * Getter for <code>sistema_vehicular.historial_repuestos.ip_usuario</code>.
     */
    public String getIpUsuario() {
        return (String) get(8);
    }

    /**
     * Setter for
     * <code>sistema_vehicular.historial_repuestos.observaciones</code>.
     */
    public HistorialRepuestosRecord setObservaciones(String value) {
        set(9, value);
        return this;
    }

    /**
     * Getter for
     * <code>sistema_vehicular.historial_repuestos.observaciones</code>.
     */
    public String getObservaciones() {
        return (String) get(9);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached HistorialRepuestosRecord
     */
    public HistorialRepuestosRecord() {
        super(HistorialRepuestos.HISTORIAL_REPUESTOS);
    }

    /**
     * Create a detached, initialised HistorialRepuestosRecord
     */
    public HistorialRepuestosRecord(Integer id, Integer repuestoId, HistorialRepuestosAccion accion, String campoModificado, String valorAnterior, String valorNuevo, String usuario, LocalDateTime fechaCambio, String ipUsuario, String observaciones) {
        super(HistorialRepuestos.HISTORIAL_REPUESTOS);

        setId(id);
        setRepuestoId(repuestoId);
        setAccion(accion);
        setCampoModificado(campoModificado);
        setValorAnterior(valorAnterior);
        setValorNuevo(valorNuevo);
        setUsuario(usuario);
        setFechaCambio(fechaCambio);
        setIpUsuario(ipUsuario);
        setObservaciones(observaciones);
        resetChangedOnNotNull();
    }

    /**
     * Create a detached, initialised HistorialRepuestosRecord
     */
    public HistorialRepuestosRecord(com.RodiejaContable.database.jooq.tables.pojos.HistorialRepuestos value) {
        super(HistorialRepuestos.HISTORIAL_REPUESTOS);

        if (value != null) {
            setId(value.getId());
            setRepuestoId(value.getRepuestoId());
            setAccion(value.getAccion());
            setCampoModificado(value.getCampoModificado());
            setValorAnterior(value.getValorAnterior());
            setValorNuevo(value.getValorNuevo());
            setUsuario(value.getUsuario());
            setFechaCambio(value.getFechaCambio());
            setIpUsuario(value.getIpUsuario());
            setObservaciones(value.getObservaciones());
            resetChangedOnNotNull();
        }
    }
}
