/*
 * This file is generated by jOOQ.
 */
package com.RodiejaContable.database.jooq.tables.records;


import com.RodiejaContable.database.jooq.tables.Marcas;

import java.time.LocalDateTime;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class MarcasRecord extends UpdatableRecordImpl<MarcasRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>sistema_vehicular.marcas.id</code>.
     */
    public MarcasRecord setId(Integer value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>sistema_vehicular.marcas.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>sistema_vehicular.marcas.nombre</code>.
     */
    public MarcasRecord setNombre(String value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>sistema_vehicular.marcas.nombre</code>.
     */
    public String getNombre() {
        return (String) get(1);
    }

    /**
     * Setter for <code>sistema_vehicular.marcas.activo</code>.
     */
    public MarcasRecord setActivo(Byte value) {
        set(2, value);
        return this;
    }

    /**
     * Getter for <code>sistema_vehicular.marcas.activo</code>.
     */
    public Byte getActivo() {
        return (Byte) get(2);
    }

    /**
     * Setter for <code>sistema_vehicular.marcas.fecha_creacion</code>.
     */
    public MarcasRecord setFechaCreacion(LocalDateTime value) {
        set(3, value);
        return this;
    }

    /**
     * Getter for <code>sistema_vehicular.marcas.fecha_creacion</code>.
     */
    public LocalDateTime getFechaCreacion() {
        return (LocalDateTime) get(3);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached MarcasRecord
     */
    public MarcasRecord() {
        super(Marcas.MARCAS);
    }

    /**
     * Create a detached, initialised MarcasRecord
     */
    public MarcasRecord(Integer id, String nombre, Byte activo, LocalDateTime fechaCreacion) {
        super(Marcas.MARCAS);

        setId(id);
        setNombre(nombre);
        setActivo(activo);
        setFechaCreacion(fechaCreacion);
        resetChangedOnNotNull();
    }

    /**
     * Create a detached, initialised MarcasRecord
     */
    public MarcasRecord(com.RodiejaContable.database.jooq.tables.pojos.Marcas value) {
        super(Marcas.MARCAS);

        if (value != null) {
            setId(value.getId());
            setNombre(value.getNombre());
            setActivo(value.getActivo());
            setFechaCreacion(value.getFechaCreacion());
            resetChangedOnNotNull();
        }
    }
}
