/*
 * This file is generated by jOOQ.
 */
package com.RodiejaContable.database.jooq.tables.records;


import com.RodiejaContable.database.jooq.tables.Modelos;

import java.time.LocalDateTime;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class ModelosRecord extends UpdatableRecordImpl<ModelosRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>sistema_vehicular.modelos.id</code>.
     */
    public ModelosRecord setId(Integer value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>sistema_vehicular.modelos.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>sistema_vehicular.modelos.marca_id</code>.
     */
    public ModelosRecord setMarcaId(Integer value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>sistema_vehicular.modelos.marca_id</code>.
     */
    public Integer getMarcaId() {
        return (Integer) get(1);
    }

    /**
     * Setter for <code>sistema_vehicular.modelos.nombre</code>.
     */
    public ModelosRecord setNombre(String value) {
        set(2, value);
        return this;
    }

    /**
     * Getter for <code>sistema_vehicular.modelos.nombre</code>.
     */
    public String getNombre() {
        return (String) get(2);
    }

    /**
     * Setter for <code>sistema_vehicular.modelos.activo</code>.
     */
    public ModelosRecord setActivo(Byte value) {
        set(3, value);
        return this;
    }

    /**
     * Getter for <code>sistema_vehicular.modelos.activo</code>.
     */
    public Byte getActivo() {
        return (Byte) get(3);
    }

    /**
     * Setter for <code>sistema_vehicular.modelos.fecha_creacion</code>.
     */
    public ModelosRecord setFechaCreacion(LocalDateTime value) {
        set(4, value);
        return this;
    }

    /**
     * Getter for <code>sistema_vehicular.modelos.fecha_creacion</code>.
     */
    public LocalDateTime getFechaCreacion() {
        return (LocalDateTime) get(4);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached ModelosRecord
     */
    public ModelosRecord() {
        super(Modelos.MODELOS);
    }

    /**
     * Create a detached, initialised ModelosRecord
     */
    public ModelosRecord(Integer id, Integer marcaId, String nombre, Byte activo, LocalDateTime fechaCreacion) {
        super(Modelos.MODELOS);

        setId(id);
        setMarcaId(marcaId);
        setNombre(nombre);
        setActivo(activo);
        setFechaCreacion(fechaCreacion);
        resetChangedOnNotNull();
    }

    /**
     * Create a detached, initialised ModelosRecord
     */
    public ModelosRecord(com.RodiejaContable.database.jooq.tables.pojos.Modelos value) {
        super(Modelos.MODELOS);

        if (value != null) {
            setId(value.getId());
            setMarcaId(value.getMarcaId());
            setNombre(value.getNombre());
            setActivo(value.getActivo());
            setFechaCreacion(value.getFechaCreacion());
            resetChangedOnNotNull();
        }
    }
}
