/*
 * This file is generated by jOOQ.
 */
package com.RodiejaContable.database.jooq.tables.records;


import com.RodiejaContable.database.jooq.enums.TransaccionesFinancierasEstado;
import com.RodiejaContable.database.jooq.tables.TransaccionesFinancieras;

import java.math.BigDecimal;
import java.time.LocalDate;
import java.time.LocalDateTime;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class TransaccionesFinancierasRecord extends UpdatableRecordImpl<TransaccionesFinancierasRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>sistema_vehicular.transacciones_financieras.id</code>.
     */
    public TransaccionesFinancierasRecord setId(Integer value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>sistema_vehicular.transacciones_financieras.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for
     * <code>sistema_vehicular.transacciones_financieras.codigo_transaccion</code>.
     */
    public TransaccionesFinancierasRecord setCodigoTransaccion(String value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for
     * <code>sistema_vehicular.transacciones_financieras.codigo_transaccion</code>.
     */
    public String getCodigoTransaccion() {
        return (String) get(1);
    }

    /**
     * Setter for
     * <code>sistema_vehicular.transacciones_financieras.fecha</code>.
     */
    public TransaccionesFinancierasRecord setFecha(LocalDate value) {
        set(2, value);
        return this;
    }

    /**
     * Getter for
     * <code>sistema_vehicular.transacciones_financieras.fecha</code>.
     */
    public LocalDate getFecha() {
        return (LocalDate) get(2);
    }

    /**
     * Setter for <code>sistema_vehicular.transacciones_financieras.dia</code>.
     */
    public TransaccionesFinancierasRecord setDia(Byte value) {
        set(3, value);
        return this;
    }

    /**
     * Getter for <code>sistema_vehicular.transacciones_financieras.dia</code>.
     */
    public Byte getDia() {
        return (Byte) get(3);
    }

    /**
     * Setter for <code>sistema_vehicular.transacciones_financieras.mes</code>.
     */
    public TransaccionesFinancierasRecord setMes(Byte value) {
        set(4, value);
        return this;
    }

    /**
     * Getter for <code>sistema_vehicular.transacciones_financieras.mes</code>.
     */
    public Byte getMes() {
        return (Byte) get(4);
    }

    /**
     * Setter for <code>sistema_vehicular.transacciones_financieras.anio</code>.
     */
    public TransaccionesFinancierasRecord setAnio(Short value) {
        set(5, value);
        return this;
    }

    /**
     * Getter for <code>sistema_vehicular.transacciones_financieras.anio</code>.
     */
    public Short getAnio() {
        return (Short) get(5);
    }

    /**
     * Setter for
     * <code>sistema_vehicular.transacciones_financieras.tipo_transaccion_id</code>.
     */
    public TransaccionesFinancierasRecord setTipoTransaccionId(Integer value) {
        set(6, value);
        return this;
    }

    /**
     * Getter for
     * <code>sistema_vehicular.transacciones_financieras.tipo_transaccion_id</code>.
     */
    public Integer getTipoTransaccionId() {
        return (Integer) get(6);
    }

    /**
     * Setter for
     * <code>sistema_vehicular.transacciones_financieras.empleado_id</code>.
     */
    public TransaccionesFinancierasRecord setEmpleadoId(Integer value) {
        set(7, value);
        return this;
    }

    /**
     * Getter for
     * <code>sistema_vehicular.transacciones_financieras.empleado_id</code>.
     */
    public Integer getEmpleadoId() {
        return (Integer) get(7);
    }

    /**
     * Setter for
     * <code>sistema_vehicular.transacciones_financieras.vehiculo_id</code>.
     */
    public TransaccionesFinancierasRecord setVehiculoId(Integer value) {
        set(8, value);
        return this;
    }

    /**
     * Getter for
     * <code>sistema_vehicular.transacciones_financieras.vehiculo_id</code>.
     */
    public Integer getVehiculoId() {
        return (Integer) get(8);
    }

    /**
     * Setter for
     * <code>sistema_vehicular.transacciones_financieras.repuesto_id</code>.
     */
    public TransaccionesFinancierasRecord setRepuestoId(Integer value) {
        set(9, value);
        return this;
    }

    /**
     * Getter for
     * <code>sistema_vehicular.transacciones_financieras.repuesto_id</code>.
     */
    public Integer getRepuestoId() {
        return (Integer) get(9);
    }

    /**
     * Setter for
     * <code>sistema_vehicular.transacciones_financieras.generacion_id</code>.
     */
    public TransaccionesFinancierasRecord setGeneracionId(Integer value) {
        set(10, value);
        return this;
    }

    /**
     * Getter for
     * <code>sistema_vehicular.transacciones_financieras.generacion_id</code>.
     */
    public Integer getGeneracionId() {
        return (Integer) get(10);
    }

    /**
     * Setter for
     * <code>sistema_vehicular.transacciones_financieras.monto</code>.
     */
    public TransaccionesFinancierasRecord setMonto(BigDecimal value) {
        set(11, value);
        return this;
    }

    /**
     * Getter for
     * <code>sistema_vehicular.transacciones_financieras.monto</code>.
     */
    public BigDecimal getMonto() {
        return (BigDecimal) get(11);
    }

    /**
     * Setter for
     * <code>sistema_vehicular.transacciones_financieras.comision_empleado</code>.
     */
    public TransaccionesFinancierasRecord setComisionEmpleado(BigDecimal value) {
        set(12, value);
        return this;
    }

    /**
     * Getter for
     * <code>sistema_vehicular.transacciones_financieras.comision_empleado</code>.
     */
    public BigDecimal getComisionEmpleado() {
        return (BigDecimal) get(12);
    }

    /**
     * Setter for
     * <code>sistema_vehicular.transacciones_financieras.descripcion</code>.
     */
    public TransaccionesFinancierasRecord setDescripcion(String value) {
        set(13, value);
        return this;
    }

    /**
     * Getter for
     * <code>sistema_vehicular.transacciones_financieras.descripcion</code>.
     */
    public String getDescripcion() {
        return (String) get(13);
    }

    /**
     * Setter for
     * <code>sistema_vehicular.transacciones_financieras.referencia</code>.
     */
    public TransaccionesFinancierasRecord setReferencia(String value) {
        set(14, value);
        return this;
    }

    /**
     * Getter for
     * <code>sistema_vehicular.transacciones_financieras.referencia</code>.
     */
    public String getReferencia() {
        return (String) get(14);
    }

    /**
     * Setter for
     * <code>sistema_vehicular.transacciones_financieras.estado</code>.
     */
    public TransaccionesFinancierasRecord setEstado(TransaccionesFinancierasEstado value) {
        set(15, value);
        return this;
    }

    /**
     * Getter for
     * <code>sistema_vehicular.transacciones_financieras.estado</code>.
     */
    public TransaccionesFinancierasEstado getEstado() {
        return (TransaccionesFinancierasEstado) get(15);
    }

    /**
     * Setter for
     * <code>sistema_vehicular.transacciones_financieras.activo</code>.
     */
    public TransaccionesFinancierasRecord setActivo(Byte value) {
        set(16, value);
        return this;
    }

    /**
     * Getter for
     * <code>sistema_vehicular.transacciones_financieras.activo</code>.
     */
    public Byte getActivo() {
        return (Byte) get(16);
    }

    /**
     * Setter for
     * <code>sistema_vehicular.transacciones_financieras.fecha_creacion</code>.
     */
    public TransaccionesFinancierasRecord setFechaCreacion(LocalDateTime value) {
        set(17, value);
        return this;
    }

    /**
     * Getter for
     * <code>sistema_vehicular.transacciones_financieras.fecha_creacion</code>.
     */
    public LocalDateTime getFechaCreacion() {
        return (LocalDateTime) get(17);
    }

    /**
     * Setter for
     * <code>sistema_vehicular.transacciones_financieras.fecha_actualizacion</code>.
     */
    public TransaccionesFinancierasRecord setFechaActualizacion(LocalDateTime value) {
        set(18, value);
        return this;
    }

    /**
     * Getter for
     * <code>sistema_vehicular.transacciones_financieras.fecha_actualizacion</code>.
     */
    public LocalDateTime getFechaActualizacion() {
        return (LocalDateTime) get(18);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached TransaccionesFinancierasRecord
     */
    public TransaccionesFinancierasRecord() {
        super(TransaccionesFinancieras.TRANSACCIONES_FINANCIERAS);
    }

    /**
     * Create a detached, initialised TransaccionesFinancierasRecord
     */
    public TransaccionesFinancierasRecord(Integer id, String codigoTransaccion, LocalDate fecha, Byte dia, Byte mes, Short anio, Integer tipoTransaccionId, Integer empleadoId, Integer vehiculoId, Integer repuestoId, Integer generacionId, BigDecimal monto, BigDecimal comisionEmpleado, String descripcion, String referencia, TransaccionesFinancierasEstado estado, Byte activo, LocalDateTime fechaCreacion, LocalDateTime fechaActualizacion) {
        super(TransaccionesFinancieras.TRANSACCIONES_FINANCIERAS);

        setId(id);
        setCodigoTransaccion(codigoTransaccion);
        setFecha(fecha);
        setDia(dia);
        setMes(mes);
        setAnio(anio);
        setTipoTransaccionId(tipoTransaccionId);
        setEmpleadoId(empleadoId);
        setVehiculoId(vehiculoId);
        setRepuestoId(repuestoId);
        setGeneracionId(generacionId);
        setMonto(monto);
        setComisionEmpleado(comisionEmpleado);
        setDescripcion(descripcion);
        setReferencia(referencia);
        setEstado(estado);
        setActivo(activo);
        setFechaCreacion(fechaCreacion);
        setFechaActualizacion(fechaActualizacion);
        resetChangedOnNotNull();
    }

    /**
     * Create a detached, initialised TransaccionesFinancierasRecord
     */
    public TransaccionesFinancierasRecord(com.RodiejaContable.database.jooq.tables.pojos.TransaccionesFinancieras value) {
        super(TransaccionesFinancieras.TRANSACCIONES_FINANCIERAS);

        if (value != null) {
            setId(value.getId());
            setCodigoTransaccion(value.getCodigoTransaccion());
            setFecha(value.getFecha());
            setDia(value.getDia());
            setMes(value.getMes());
            setAnio(value.getAnio());
            setTipoTransaccionId(value.getTipoTransaccionId());
            setEmpleadoId(value.getEmpleadoId());
            setVehiculoId(value.getVehiculoId());
            setRepuestoId(value.getRepuestoId());
            setGeneracionId(value.getGeneracionId());
            setMonto(value.getMonto());
            setComisionEmpleado(value.getComisionEmpleado());
            setDescripcion(value.getDescripcion());
            setReferencia(value.getReferencia());
            setEstado(value.getEstado());
            setActivo(value.getActivo());
            setFechaCreacion(value.getFechaCreacion());
            setFechaActualizacion(value.getFechaActualizacion());
            resetChangedOnNotNull();
        }
    }
}
