/*
 * This file is generated by jOOQ.
 */
package com.RodiejaContable.database.jooq.tables.records;


import com.RodiejaContable.database.jooq.tables.VistaVentasPorEmpleado;

import java.math.BigDecimal;

import org.jooq.impl.TableRecordImpl;


/**
 * VIEW
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class VistaVentasPorEmpleadoRecord extends TableRecordImpl<VistaVentasPorEmpleadoRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for
     * <code>sistema_vehicular.vista_ventas_por_empleado.empleado</code>.
     */
    public VistaVentasPorEmpleadoRecord setEmpleado(String value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for
     * <code>sistema_vehicular.vista_ventas_por_empleado.empleado</code>.
     */
    public String getEmpleado() {
        return (String) get(0);
    }

    /**
     * Setter for
     * <code>sistema_vehicular.vista_ventas_por_empleado.total_transacciones</code>.
     */
    public VistaVentasPorEmpleadoRecord setTotalTransacciones(Long value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for
     * <code>sistema_vehicular.vista_ventas_por_empleado.total_transacciones</code>.
     */
    public Long getTotalTransacciones() {
        return (Long) get(1);
    }

    /**
     * Setter for
     * <code>sistema_vehicular.vista_ventas_por_empleado.transacciones_venta</code>.
     */
    public VistaVentasPorEmpleadoRecord setTransaccionesVenta(Long value) {
        set(2, value);
        return this;
    }

    /**
     * Getter for
     * <code>sistema_vehicular.vista_ventas_por_empleado.transacciones_venta</code>.
     */
    public Long getTransaccionesVenta() {
        return (Long) get(2);
    }

    /**
     * Setter for
     * <code>sistema_vehicular.vista_ventas_por_empleado.total_ventas</code>.
     */
    public VistaVentasPorEmpleadoRecord setTotalVentas(BigDecimal value) {
        set(3, value);
        return this;
    }

    /**
     * Getter for
     * <code>sistema_vehicular.vista_ventas_por_empleado.total_ventas</code>.
     */
    public BigDecimal getTotalVentas() {
        return (BigDecimal) get(3);
    }

    /**
     * Setter for
     * <code>sistema_vehicular.vista_ventas_por_empleado.total_comisiones</code>.
     */
    public VistaVentasPorEmpleadoRecord setTotalComisiones(BigDecimal value) {
        set(4, value);
        return this;
    }

    /**
     * Getter for
     * <code>sistema_vehicular.vista_ventas_por_empleado.total_comisiones</code>.
     */
    public BigDecimal getTotalComisiones() {
        return (BigDecimal) get(4);
    }

    /**
     * Setter for
     * <code>sistema_vehicular.vista_ventas_por_empleado.promedio_venta</code>.
     */
    public VistaVentasPorEmpleadoRecord setPromedioVenta(BigDecimal value) {
        set(5, value);
        return this;
    }

    /**
     * Getter for
     * <code>sistema_vehicular.vista_ventas_por_empleado.promedio_venta</code>.
     */
    public BigDecimal getPromedioVenta() {
        return (BigDecimal) get(5);
    }

    /**
     * Setter for
     * <code>sistema_vehicular.vista_ventas_por_empleado.porcentaje_comision</code>.
     */
    public VistaVentasPorEmpleadoRecord setPorcentajeComision(BigDecimal value) {
        set(6, value);
        return this;
    }

    /**
     * Getter for
     * <code>sistema_vehicular.vista_ventas_por_empleado.porcentaje_comision</code>.
     */
    public BigDecimal getPorcentajeComision() {
        return (BigDecimal) get(6);
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached VistaVentasPorEmpleadoRecord
     */
    public VistaVentasPorEmpleadoRecord() {
        super(VistaVentasPorEmpleado.VISTA_VENTAS_POR_EMPLEADO);
    }

    /**
     * Create a detached, initialised VistaVentasPorEmpleadoRecord
     */
    public VistaVentasPorEmpleadoRecord(String empleado, Long totalTransacciones, Long transaccionesVenta, BigDecimal totalVentas, BigDecimal totalComisiones, BigDecimal promedioVenta, BigDecimal porcentajeComision) {
        super(VistaVentasPorEmpleado.VISTA_VENTAS_POR_EMPLEADO);

        setEmpleado(empleado);
        setTotalTransacciones(totalTransacciones);
        setTransaccionesVenta(transaccionesVenta);
        setTotalVentas(totalVentas);
        setTotalComisiones(totalComisiones);
        setPromedioVenta(promedioVenta);
        setPorcentajeComision(porcentajeComision);
        resetChangedOnNotNull();
    }

    /**
     * Create a detached, initialised VistaVentasPorEmpleadoRecord
     */
    public VistaVentasPorEmpleadoRecord(com.RodiejaContable.database.jooq.tables.pojos.VistaVentasPorEmpleado value) {
        super(VistaVentasPorEmpleado.VISTA_VENTAS_POR_EMPLEADO);

        if (value != null) {
            setEmpleado(value.getEmpleado());
            setTotalTransacciones(value.getTotalTransacciones());
            setTransaccionesVenta(value.getTransaccionesVenta());
            setTotalVentas(value.getTotalVentas());
            setTotalComisiones(value.getTotalComisiones());
            setPromedioVenta(value.getPromedioVenta());
            setPorcentajeComision(value.getPorcentajeComision());
            resetChangedOnNotNull();
        }
    }
}
