/*
 * This file is generated by jOOQ.
 */
package com.RodiejaContable.database.jooq.tables.records;


import com.RodiejaContable.database.jooq.tables.VistaDashboardEjecutivo;

import java.math.BigDecimal;

import org.jooq.impl.TableRecordImpl;


/**
 * VIEW
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class VistaDashboardEjecutivoRecord extends TableRecordImpl<VistaDashboardEjecutivoRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for
     * <code>sistema_vehicular.vista_dashboard_ejecutivo.seccion</code>.
     */
    public VistaDashboardEjecutivoRecord setSeccion(String value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for
     * <code>sistema_vehicular.vista_dashboard_ejecutivo.seccion</code>.
     */
    public String getSeccion() {
        return (String) get(0);
    }

    /**
     * Setter for
     * <code>sistema_vehicular.vista_dashboard_ejecutivo.total_vehiculos</code>.
     */
    public VistaDashboardEjecutivoRecord setTotalVehiculos(Long value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for
     * <code>sistema_vehicular.vista_dashboard_ejecutivo.total_vehiculos</code>.
     */
    public Long getTotalVehiculos() {
        return (Long) get(1);
    }

    /**
     * Setter for
     * <code>sistema_vehicular.vista_dashboard_ejecutivo.vehiculos_disponibles</code>.
     */
    public VistaDashboardEjecutivoRecord setVehiculosDisponibles(Long value) {
        set(2, value);
        return this;
    }

    /**
     * Getter for
     * <code>sistema_vehicular.vista_dashboard_ejecutivo.vehiculos_disponibles</code>.
     */
    public Long getVehiculosDisponibles() {
        return (Long) get(2);
    }

    /**
     * Setter for
     * <code>sistema_vehicular.vista_dashboard_ejecutivo.vehiculos_vendidos</code>.
     */
    public VistaDashboardEjecutivoRecord setVehiculosVendidos(Long value) {
        set(3, value);
        return this;
    }

    /**
     * Getter for
     * <code>sistema_vehicular.vista_dashboard_ejecutivo.vehiculos_vendidos</code>.
     */
    public Long getVehiculosVendidos() {
        return (Long) get(3);
    }

    /**
     * Setter for
     * <code>sistema_vehicular.vista_dashboard_ejecutivo.total_repuestos</code>.
     */
    public VistaDashboardEjecutivoRecord setTotalRepuestos(Long value) {
        set(4, value);
        return this;
    }

    /**
     * Getter for
     * <code>sistema_vehicular.vista_dashboard_ejecutivo.total_repuestos</code>.
     */
    public Long getTotalRepuestos() {
        return (Long) get(4);
    }

    /**
     * Setter for
     * <code>sistema_vehicular.vista_dashboard_ejecutivo.repuestos_stock</code>.
     */
    public VistaDashboardEjecutivoRecord setRepuestosStock(Long value) {
        set(5, value);
        return this;
    }

    /**
     * Getter for
     * <code>sistema_vehicular.vista_dashboard_ejecutivo.repuestos_stock</code>.
     */
    public Long getRepuestosStock() {
        return (Long) get(5);
    }

    /**
     * Setter for
     * <code>sistema_vehicular.vista_dashboard_ejecutivo.inversion_total</code>.
     */
    public VistaDashboardEjecutivoRecord setInversionTotal(BigDecimal value) {
        set(6, value);
        return this;
    }

    /**
     * Getter for
     * <code>sistema_vehicular.vista_dashboard_ejecutivo.inversion_total</code>.
     */
    public BigDecimal getInversionTotal() {
        return (BigDecimal) get(6);
    }

    /**
     * Setter for
     * <code>sistema_vehicular.vista_dashboard_ejecutivo.ingresos_totales</code>.
     */
    public VistaDashboardEjecutivoRecord setIngresosTotales(BigDecimal value) {
        set(7, value);
        return this;
    }

    /**
     * Getter for
     * <code>sistema_vehicular.vista_dashboard_ejecutivo.ingresos_totales</code>.
     */
    public BigDecimal getIngresosTotales() {
        return (BigDecimal) get(7);
    }

    /**
     * Setter for
     * <code>sistema_vehicular.vista_dashboard_ejecutivo.egresos_totales</code>.
     */
    public VistaDashboardEjecutivoRecord setEgresosTotales(BigDecimal value) {
        set(8, value);
        return this;
    }

    /**
     * Getter for
     * <code>sistema_vehicular.vista_dashboard_ejecutivo.egresos_totales</code>.
     */
    public BigDecimal getEgresosTotales() {
        return (BigDecimal) get(8);
    }

    /**
     * Setter for
     * <code>sistema_vehicular.vista_dashboard_ejecutivo.balance_neto_total</code>.
     */
    public VistaDashboardEjecutivoRecord setBalanceNetoTotal(BigDecimal value) {
        set(9, value);
        return this;
    }

    /**
     * Getter for
     * <code>sistema_vehicular.vista_dashboard_ejecutivo.balance_neto_total</code>.
     */
    public BigDecimal getBalanceNetoTotal() {
        return (BigDecimal) get(9);
    }

    /**
     * Setter for
     * <code>sistema_vehicular.vista_dashboard_ejecutivo.roi_promedio</code>.
     */
    public VistaDashboardEjecutivoRecord setRoiPromedio(BigDecimal value) {
        set(10, value);
        return this;
    }

    /**
     * Getter for
     * <code>sistema_vehicular.vista_dashboard_ejecutivo.roi_promedio</code>.
     */
    public BigDecimal getRoiPromedio() {
        return (BigDecimal) get(10);
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached VistaDashboardEjecutivoRecord
     */
    public VistaDashboardEjecutivoRecord() {
        super(VistaDashboardEjecutivo.VISTA_DASHBOARD_EJECUTIVO);
    }

    /**
     * Create a detached, initialised VistaDashboardEjecutivoRecord
     */
    public VistaDashboardEjecutivoRecord(String seccion, Long totalVehiculos, Long vehiculosDisponibles, Long vehiculosVendidos, Long totalRepuestos, Long repuestosStock, BigDecimal inversionTotal, BigDecimal ingresosTotales, BigDecimal egresosTotales, BigDecimal balanceNetoTotal, BigDecimal roiPromedio) {
        super(VistaDashboardEjecutivo.VISTA_DASHBOARD_EJECUTIVO);

        setSeccion(seccion);
        setTotalVehiculos(totalVehiculos);
        setVehiculosDisponibles(vehiculosDisponibles);
        setVehiculosVendidos(vehiculosVendidos);
        setTotalRepuestos(totalRepuestos);
        setRepuestosStock(repuestosStock);
        setInversionTotal(inversionTotal);
        setIngresosTotales(ingresosTotales);
        setEgresosTotales(egresosTotales);
        setBalanceNetoTotal(balanceNetoTotal);
        setRoiPromedio(roiPromedio);
        resetChangedOnNotNull();
    }

    /**
     * Create a detached, initialised VistaDashboardEjecutivoRecord
     */
    public VistaDashboardEjecutivoRecord(com.RodiejaContable.database.jooq.tables.pojos.VistaDashboardEjecutivo value) {
        super(VistaDashboardEjecutivo.VISTA_DASHBOARD_EJECUTIVO);

        if (value != null) {
            setSeccion(value.getSeccion());
            setTotalVehiculos(value.getTotalVehiculos());
            setVehiculosDisponibles(value.getVehiculosDisponibles());
            setVehiculosVendidos(value.getVehiculosVendidos());
            setTotalRepuestos(value.getTotalRepuestos());
            setRepuestosStock(value.getRepuestosStock());
            setInversionTotal(value.getInversionTotal());
            setIngresosTotales(value.getIngresosTotales());
            setEgresosTotales(value.getEgresosTotales());
            setBalanceNetoTotal(value.getBalanceNetoTotal());
            setRoiPromedio(value.getRoiPromedio());
            resetChangedOnNotNull();
        }
    }
}
