/*
 * This file is generated by jOOQ.
 */
package com.RodiejaContable.database.jooq.tables.records;


import com.RodiejaContable.database.jooq.enums.VistaInventarioCriticoEstado;
import com.RodiejaContable.database.jooq.enums.VistaInventarioCriticoParteVehiculo;
import com.RodiejaContable.database.jooq.tables.VistaInventarioCritico;

import java.math.BigDecimal;

import org.jooq.impl.TableRecordImpl;


/**
 * VIEW
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class VistaInventarioCriticoRecord extends TableRecordImpl<VistaInventarioCriticoRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for
     * <code>sistema_vehicular.vista_inventario_critico.codigo_repuesto</code>.
     */
    public VistaInventarioCriticoRecord setCodigoRepuesto(String value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for
     * <code>sistema_vehicular.vista_inventario_critico.codigo_repuesto</code>.
     */
    public String getCodigoRepuesto() {
        return (String) get(0);
    }

    /**
     * Setter for
     * <code>sistema_vehicular.vista_inventario_critico.parte_vehiculo</code>.
     */
    public VistaInventarioCriticoRecord setParteVehiculo(VistaInventarioCriticoParteVehiculo value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for
     * <code>sistema_vehicular.vista_inventario_critico.parte_vehiculo</code>.
     */
    public VistaInventarioCriticoParteVehiculo getParteVehiculo() {
        return (VistaInventarioCriticoParteVehiculo) get(1);
    }

    /**
     * Setter for
     * <code>sistema_vehicular.vista_inventario_critico.descripcion</code>.
     */
    public VistaInventarioCriticoRecord setDescripcion(String value) {
        set(2, value);
        return this;
    }

    /**
     * Getter for
     * <code>sistema_vehicular.vista_inventario_critico.descripcion</code>.
     */
    public String getDescripcion() {
        return (String) get(2);
    }

    /**
     * Setter for
     * <code>sistema_vehicular.vista_inventario_critico.precio_costo</code>.
     */
    public VistaInventarioCriticoRecord setPrecioCosto(BigDecimal value) {
        set(3, value);
        return this;
    }

    /**
     * Getter for
     * <code>sistema_vehicular.vista_inventario_critico.precio_costo</code>.
     */
    public BigDecimal getPrecioCosto() {
        return (BigDecimal) get(3);
    }

    /**
     * Setter for
     * <code>sistema_vehicular.vista_inventario_critico.precio_venta</code>.
     */
    public VistaInventarioCriticoRecord setPrecioVenta(BigDecimal value) {
        set(4, value);
        return this;
    }

    /**
     * Getter for
     * <code>sistema_vehicular.vista_inventario_critico.precio_venta</code>.
     */
    public BigDecimal getPrecioVenta() {
        return (BigDecimal) get(4);
    }

    /**
     * Setter for
     * <code>sistema_vehicular.vista_inventario_critico.precio_mayoreo</code>.
     */
    public VistaInventarioCriticoRecord setPrecioMayoreo(BigDecimal value) {
        set(5, value);
        return this;
    }

    /**
     * Getter for
     * <code>sistema_vehicular.vista_inventario_critico.precio_mayoreo</code>.
     */
    public BigDecimal getPrecioMayoreo() {
        return (BigDecimal) get(5);
    }

    /**
     * Setter for
     * <code>sistema_vehicular.vista_inventario_critico.formula_15</code>.
     */
    public VistaInventarioCriticoRecord setFormula_15(BigDecimal value) {
        set(6, value);
        return this;
    }

    /**
     * Getter for
     * <code>sistema_vehicular.vista_inventario_critico.formula_15</code>.
     */
    public BigDecimal getFormula_15() {
        return (BigDecimal) get(6);
    }

    /**
     * Setter for
     * <code>sistema_vehicular.vista_inventario_critico.formula_30</code>.
     */
    public VistaInventarioCriticoRecord setFormula_30(BigDecimal value) {
        set(7, value);
        return this;
    }

    /**
     * Getter for
     * <code>sistema_vehicular.vista_inventario_critico.formula_30</code>.
     */
    public BigDecimal getFormula_30() {
        return (BigDecimal) get(7);
    }

    /**
     * Setter for
     * <code>sistema_vehicular.vista_inventario_critico.estado</code>.
     */
    public VistaInventarioCriticoRecord setEstado(VistaInventarioCriticoEstado value) {
        set(8, value);
        return this;
    }

    /**
     * Getter for
     * <code>sistema_vehicular.vista_inventario_critico.estado</code>.
     */
    public VistaInventarioCriticoEstado getEstado() {
        return (VistaInventarioCriticoEstado) get(8);
    }

    /**
     * Setter for
     * <code>sistema_vehicular.vista_inventario_critico.codigo_ubicacion</code>.
     */
    public VistaInventarioCriticoRecord setCodigoUbicacion(String value) {
        set(9, value);
        return this;
    }

    /**
     * Getter for
     * <code>sistema_vehicular.vista_inventario_critico.codigo_ubicacion</code>.
     */
    public String getCodigoUbicacion() {
        return (String) get(9);
    }

    /**
     * Setter for
     * <code>sistema_vehicular.vista_inventario_critico.vehiculo_origen</code>.
     */
    public VistaInventarioCriticoRecord setVehiculoOrigen(String value) {
        set(10, value);
        return this;
    }

    /**
     * Getter for
     * <code>sistema_vehicular.vista_inventario_critico.vehiculo_origen</code>.
     */
    public String getVehiculoOrigen() {
        return (String) get(10);
    }

    /**
     * Setter for
     * <code>sistema_vehicular.vista_inventario_critico.anio_vehiculo</code>.
     */
    public VistaInventarioCriticoRecord setAnioVehiculo(Integer value) {
        set(11, value);
        return this;
    }

    /**
     * Getter for
     * <code>sistema_vehicular.vista_inventario_critico.anio_vehiculo</code>.
     */
    public Integer getAnioVehiculo() {
        return (Integer) get(11);
    }

    /**
     * Setter for
     * <code>sistema_vehicular.vista_inventario_critico.anio_registro</code>.
     */
    public VistaInventarioCriticoRecord setAnioRegistro(Short value) {
        set(12, value);
        return this;
    }

    /**
     * Getter for
     * <code>sistema_vehicular.vista_inventario_critico.anio_registro</code>.
     */
    public Short getAnioRegistro() {
        return (Short) get(12);
    }

    /**
     * Setter for
     * <code>sistema_vehicular.vista_inventario_critico.mes_registro</code>.
     */
    public VistaInventarioCriticoRecord setMesRegistro(Byte value) {
        set(13, value);
        return this;
    }

    /**
     * Getter for
     * <code>sistema_vehicular.vista_inventario_critico.mes_registro</code>.
     */
    public Byte getMesRegistro() {
        return (Byte) get(13);
    }

    /**
     * Setter for
     * <code>sistema_vehicular.vista_inventario_critico.dias_en_inventario</code>.
     */
    public VistaInventarioCriticoRecord setDiasEnInventario(Integer value) {
        set(14, value);
        return this;
    }

    /**
     * Getter for
     * <code>sistema_vehicular.vista_inventario_critico.dias_en_inventario</code>.
     */
    public Integer getDiasEnInventario() {
        return (Integer) get(14);
    }

    /**
     * Setter for
     * <code>sistema_vehicular.vista_inventario_critico.clasificacion_margen</code>.
     */
    public VistaInventarioCriticoRecord setClasificacionMargen(String value) {
        set(15, value);
        return this;
    }

    /**
     * Getter for
     * <code>sistema_vehicular.vista_inventario_critico.clasificacion_margen</code>.
     */
    public String getClasificacionMargen() {
        return (String) get(15);
    }

    /**
     * Setter for
     * <code>sistema_vehicular.vista_inventario_critico.clasificacion_rotacion</code>.
     */
    public VistaInventarioCriticoRecord setClasificacionRotacion(String value) {
        set(16, value);
        return this;
    }

    /**
     * Getter for
     * <code>sistema_vehicular.vista_inventario_critico.clasificacion_rotacion</code>.
     */
    public String getClasificacionRotacion() {
        return (String) get(16);
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached VistaInventarioCriticoRecord
     */
    public VistaInventarioCriticoRecord() {
        super(VistaInventarioCritico.VISTA_INVENTARIO_CRITICO);
    }

    /**
     * Create a detached, initialised VistaInventarioCriticoRecord
     */
    public VistaInventarioCriticoRecord(String codigoRepuesto, VistaInventarioCriticoParteVehiculo parteVehiculo, String descripcion, BigDecimal precioCosto, BigDecimal precioVenta, BigDecimal precioMayoreo, BigDecimal formula_15, BigDecimal formula_30, VistaInventarioCriticoEstado estado, String codigoUbicacion, String vehiculoOrigen, Integer anioVehiculo, Short anioRegistro, Byte mesRegistro, Integer diasEnInventario, String clasificacionMargen, String clasificacionRotacion) {
        super(VistaInventarioCritico.VISTA_INVENTARIO_CRITICO);

        setCodigoRepuesto(codigoRepuesto);
        setParteVehiculo(parteVehiculo);
        setDescripcion(descripcion);
        setPrecioCosto(precioCosto);
        setPrecioVenta(precioVenta);
        setPrecioMayoreo(precioMayoreo);
        setFormula_15(formula_15);
        setFormula_30(formula_30);
        setEstado(estado);
        setCodigoUbicacion(codigoUbicacion);
        setVehiculoOrigen(vehiculoOrigen);
        setAnioVehiculo(anioVehiculo);
        setAnioRegistro(anioRegistro);
        setMesRegistro(mesRegistro);
        setDiasEnInventario(diasEnInventario);
        setClasificacionMargen(clasificacionMargen);
        setClasificacionRotacion(clasificacionRotacion);
        resetChangedOnNotNull();
    }

    /**
     * Create a detached, initialised VistaInventarioCriticoRecord
     */
    public VistaInventarioCriticoRecord(com.RodiejaContable.database.jooq.tables.pojos.VistaInventarioCritico value) {
        super(VistaInventarioCritico.VISTA_INVENTARIO_CRITICO);

        if (value != null) {
            setCodigoRepuesto(value.getCodigoRepuesto());
            setParteVehiculo(value.getParteVehiculo());
            setDescripcion(value.getDescripcion());
            setPrecioCosto(value.getPrecioCosto());
            setPrecioVenta(value.getPrecioVenta());
            setPrecioMayoreo(value.getPrecioMayoreo());
            setFormula_15(value.getFormula_15());
            setFormula_30(value.getFormula_30());
            setEstado(value.getEstado());
            setCodigoUbicacion(value.getCodigoUbicacion());
            setVehiculoOrigen(value.getVehiculoOrigen());
            setAnioVehiculo(value.getAnioVehiculo());
            setAnioRegistro(value.getAnioRegistro());
            setMesRegistro(value.getMesRegistro());
            setDiasEnInventario(value.getDiasEnInventario());
            setClasificacionMargen(value.getClasificacionMargen());
            setClasificacionRotacion(value.getClasificacionRotacion());
            resetChangedOnNotNull();
        }
    }
}
