/*
 * This file is generated by jOOQ.
 */
package com.RodiejaContable.database.jooq.tables.records;


import com.RodiejaContable.database.jooq.tables.VistaAnalisisFinancieroMensual;

import java.math.BigDecimal;

import org.jooq.impl.TableRecordImpl;


/**
 * VIEW
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class VistaAnalisisFinancieroMensualRecord extends TableRecordImpl<VistaAnalisisFinancieroMensualRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for
     * <code>sistema_vehicular.vista_analisis_financiero_mensual.anio</code>.
     */
    public VistaAnalisisFinancieroMensualRecord setAnio(Integer value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for
     * <code>sistema_vehicular.vista_analisis_financiero_mensual.anio</code>.
     */
    public Integer getAnio() {
        return (Integer) get(0);
    }

    /**
     * Setter for
     * <code>sistema_vehicular.vista_analisis_financiero_mensual.mes</code>.
     */
    public VistaAnalisisFinancieroMensualRecord setMes(Integer value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for
     * <code>sistema_vehicular.vista_analisis_financiero_mensual.mes</code>.
     */
    public Integer getMes() {
        return (Integer) get(1);
    }

    /**
     * Setter for
     * <code>sistema_vehicular.vista_analisis_financiero_mensual.nombre_mes</code>.
     */
    public VistaAnalisisFinancieroMensualRecord setNombreMes(String value) {
        set(2, value);
        return this;
    }

    /**
     * Getter for
     * <code>sistema_vehicular.vista_analisis_financiero_mensual.nombre_mes</code>.
     */
    public String getNombreMes() {
        return (String) get(2);
    }

    /**
     * Setter for
     * <code>sistema_vehicular.vista_analisis_financiero_mensual.total_transacciones</code>.
     */
    public VistaAnalisisFinancieroMensualRecord setTotalTransacciones(Long value) {
        set(3, value);
        return this;
    }

    /**
     * Getter for
     * <code>sistema_vehicular.vista_analisis_financiero_mensual.total_transacciones</code>.
     */
    public Long getTotalTransacciones() {
        return (Long) get(3);
    }

    /**
     * Setter for
     * <code>sistema_vehicular.vista_analisis_financiero_mensual.total_ingresos</code>.
     */
    public VistaAnalisisFinancieroMensualRecord setTotalIngresos(BigDecimal value) {
        set(4, value);
        return this;
    }

    /**
     * Getter for
     * <code>sistema_vehicular.vista_analisis_financiero_mensual.total_ingresos</code>.
     */
    public BigDecimal getTotalIngresos() {
        return (BigDecimal) get(4);
    }

    /**
     * Setter for
     * <code>sistema_vehicular.vista_analisis_financiero_mensual.total_egresos</code>.
     */
    public VistaAnalisisFinancieroMensualRecord setTotalEgresos(BigDecimal value) {
        set(5, value);
        return this;
    }

    /**
     * Getter for
     * <code>sistema_vehicular.vista_analisis_financiero_mensual.total_egresos</code>.
     */
    public BigDecimal getTotalEgresos() {
        return (BigDecimal) get(5);
    }

    /**
     * Setter for
     * <code>sistema_vehicular.vista_analisis_financiero_mensual.balance_neto</code>.
     */
    public VistaAnalisisFinancieroMensualRecord setBalanceNeto(BigDecimal value) {
        set(6, value);
        return this;
    }

    /**
     * Getter for
     * <code>sistema_vehicular.vista_analisis_financiero_mensual.balance_neto</code>.
     */
    public BigDecimal getBalanceNeto() {
        return (BigDecimal) get(6);
    }

    /**
     * Setter for
     * <code>sistema_vehicular.vista_analisis_financiero_mensual.total_comisiones</code>.
     */
    public VistaAnalisisFinancieroMensualRecord setTotalComisiones(BigDecimal value) {
        set(7, value);
        return this;
    }

    /**
     * Getter for
     * <code>sistema_vehicular.vista_analisis_financiero_mensual.total_comisiones</code>.
     */
    public BigDecimal getTotalComisiones() {
        return (BigDecimal) get(7);
    }

    /**
     * Setter for
     * <code>sistema_vehicular.vista_analisis_financiero_mensual.vehiculos_vendidos</code>.
     */
    public VistaAnalisisFinancieroMensualRecord setVehiculosVendidos(Long value) {
        set(8, value);
        return this;
    }

    /**
     * Getter for
     * <code>sistema_vehicular.vista_analisis_financiero_mensual.vehiculos_vendidos</code>.
     */
    public Long getVehiculosVendidos() {
        return (Long) get(8);
    }

    /**
     * Setter for
     * <code>sistema_vehicular.vista_analisis_financiero_mensual.repuestos_vendidos</code>.
     */
    public VistaAnalisisFinancieroMensualRecord setRepuestosVendidos(Long value) {
        set(9, value);
        return this;
    }

    /**
     * Getter for
     * <code>sistema_vehicular.vista_analisis_financiero_mensual.repuestos_vendidos</code>.
     */
    public Long getRepuestosVendidos() {
        return (Long) get(9);
    }

    /**
     * Setter for
     * <code>sistema_vehicular.vista_analisis_financiero_mensual.promedio_venta</code>.
     */
    public VistaAnalisisFinancieroMensualRecord setPromedioVenta(BigDecimal value) {
        set(10, value);
        return this;
    }

    /**
     * Getter for
     * <code>sistema_vehicular.vista_analisis_financiero_mensual.promedio_venta</code>.
     */
    public BigDecimal getPromedioVenta() {
        return (BigDecimal) get(10);
    }

    /**
     * Setter for
     * <code>sistema_vehicular.vista_analisis_financiero_mensual.ratio_ingresos_egresos</code>.
     */
    public VistaAnalisisFinancieroMensualRecord setRatioIngresosEgresos(BigDecimal value) {
        set(11, value);
        return this;
    }

    /**
     * Getter for
     * <code>sistema_vehicular.vista_analisis_financiero_mensual.ratio_ingresos_egresos</code>.
     */
    public BigDecimal getRatioIngresosEgresos() {
        return (BigDecimal) get(11);
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached VistaAnalisisFinancieroMensualRecord
     */
    public VistaAnalisisFinancieroMensualRecord() {
        super(VistaAnalisisFinancieroMensual.VISTA_ANALISIS_FINANCIERO_MENSUAL);
    }

    /**
     * Create a detached, initialised VistaAnalisisFinancieroMensualRecord
     */
    public VistaAnalisisFinancieroMensualRecord(Integer anio, Integer mes, String nombreMes, Long totalTransacciones, BigDecimal totalIngresos, BigDecimal totalEgresos, BigDecimal balanceNeto, BigDecimal totalComisiones, Long vehiculosVendidos, Long repuestosVendidos, BigDecimal promedioVenta, BigDecimal ratioIngresosEgresos) {
        super(VistaAnalisisFinancieroMensual.VISTA_ANALISIS_FINANCIERO_MENSUAL);

        setAnio(anio);
        setMes(mes);
        setNombreMes(nombreMes);
        setTotalTransacciones(totalTransacciones);
        setTotalIngresos(totalIngresos);
        setTotalEgresos(totalEgresos);
        setBalanceNeto(balanceNeto);
        setTotalComisiones(totalComisiones);
        setVehiculosVendidos(vehiculosVendidos);
        setRepuestosVendidos(repuestosVendidos);
        setPromedioVenta(promedioVenta);
        setRatioIngresosEgresos(ratioIngresosEgresos);
        resetChangedOnNotNull();
    }

    /**
     * Create a detached, initialised VistaAnalisisFinancieroMensualRecord
     */
    public VistaAnalisisFinancieroMensualRecord(com.RodiejaContable.database.jooq.tables.pojos.VistaAnalisisFinancieroMensual value) {
        super(VistaAnalisisFinancieroMensual.VISTA_ANALISIS_FINANCIERO_MENSUAL);

        if (value != null) {
            setAnio(value.getAnio());
            setMes(value.getMes());
            setNombreMes(value.getNombreMes());
            setTotalTransacciones(value.getTotalTransacciones());
            setTotalIngresos(value.getTotalIngresos());
            setTotalEgresos(value.getTotalEgresos());
            setBalanceNeto(value.getBalanceNeto());
            setTotalComisiones(value.getTotalComisiones());
            setVehiculosVendidos(value.getVehiculosVendidos());
            setRepuestosVendidos(value.getRepuestosVendidos());
            setPromedioVenta(value.getPromedioVenta());
            setRatioIngresosEgresos(value.getRatioIngresosEgresos());
            resetChangedOnNotNull();
        }
    }
}
