/*
 * This file is generated by jOOQ.
 */
package com.RodiejaContable.database.jooq.tables.records;


import com.RodiejaContable.database.jooq.tables.VistaResumenGeneraciones;

import java.math.BigDecimal;

import org.jooq.impl.TableRecordImpl;


/**
 * VIEW
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class VistaResumenGeneracionesRecord extends TableRecordImpl<VistaResumenGeneracionesRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for
     * <code>sistema_vehicular.vista_resumen_generaciones.generacion_id</code>.
     */
    public VistaResumenGeneracionesRecord setGeneracionId(Integer value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for
     * <code>sistema_vehicular.vista_resumen_generaciones.generacion_id</code>.
     */
    public Integer getGeneracionId() {
        return (Integer) get(0);
    }

    /**
     * Setter for
     * <code>sistema_vehicular.vista_resumen_generaciones.marca</code>.
     */
    public VistaResumenGeneracionesRecord setMarca(String value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for
     * <code>sistema_vehicular.vista_resumen_generaciones.marca</code>.
     */
    public String getMarca() {
        return (String) get(1);
    }

    /**
     * Setter for
     * <code>sistema_vehicular.vista_resumen_generaciones.modelo</code>.
     */
    public VistaResumenGeneracionesRecord setModelo(String value) {
        set(2, value);
        return this;
    }

    /**
     * Getter for
     * <code>sistema_vehicular.vista_resumen_generaciones.modelo</code>.
     */
    public String getModelo() {
        return (String) get(2);
    }

    /**
     * Setter for
     * <code>sistema_vehicular.vista_resumen_generaciones.generacion</code>.
     */
    public VistaResumenGeneracionesRecord setGeneracion(String value) {
        set(3, value);
        return this;
    }

    /**
     * Getter for
     * <code>sistema_vehicular.vista_resumen_generaciones.generacion</code>.
     */
    public String getGeneracion() {
        return (String) get(3);
    }

    /**
     * Setter for
     * <code>sistema_vehicular.vista_resumen_generaciones.descripcion</code>.
     */
    public VistaResumenGeneracionesRecord setDescripcion(String value) {
        set(4, value);
        return this;
    }

    /**
     * Getter for
     * <code>sistema_vehicular.vista_resumen_generaciones.descripcion</code>.
     */
    public String getDescripcion() {
        return (String) get(4);
    }

    /**
     * Setter for
     * <code>sistema_vehicular.vista_resumen_generaciones.clave_generacion</code>.
     */
    public VistaResumenGeneracionesRecord setClaveGeneracion(String value) {
        set(5, value);
        return this;
    }

    /**
     * Getter for
     * <code>sistema_vehicular.vista_resumen_generaciones.clave_generacion</code>.
     */
    public String getClaveGeneracion() {
        return (String) get(5);
    }

    /**
     * Setter for
     * <code>sistema_vehicular.vista_resumen_generaciones.anio_inicio</code>.
     */
    public VistaResumenGeneracionesRecord setAnioInicio(Integer value) {
        set(6, value);
        return this;
    }

    /**
     * Getter for
     * <code>sistema_vehicular.vista_resumen_generaciones.anio_inicio</code>.
     */
    public Integer getAnioInicio() {
        return (Integer) get(6);
    }

    /**
     * Setter for
     * <code>sistema_vehicular.vista_resumen_generaciones.anio_fin</code>.
     */
    public VistaResumenGeneracionesRecord setAnioFin(Integer value) {
        set(7, value);
        return this;
    }

    /**
     * Getter for
     * <code>sistema_vehicular.vista_resumen_generaciones.anio_fin</code>.
     */
    public Integer getAnioFin() {
        return (Integer) get(7);
    }

    /**
     * Setter for
     * <code>sistema_vehicular.vista_resumen_generaciones.total_vehiculos</code>.
     */
    public VistaResumenGeneracionesRecord setTotalVehiculos(Long value) {
        set(8, value);
        return this;
    }

    /**
     * Getter for
     * <code>sistema_vehicular.vista_resumen_generaciones.total_vehiculos</code>.
     */
    public Long getTotalVehiculos() {
        return (Long) get(8);
    }

    /**
     * Setter for
     * <code>sistema_vehicular.vista_resumen_generaciones.total_repuestos</code>.
     */
    public VistaResumenGeneracionesRecord setTotalRepuestos(Long value) {
        set(9, value);
        return this;
    }

    /**
     * Getter for
     * <code>sistema_vehicular.vista_resumen_generaciones.total_repuestos</code>.
     */
    public Long getTotalRepuestos() {
        return (Long) get(9);
    }

    /**
     * Setter for
     * <code>sistema_vehicular.vista_resumen_generaciones.total_inversion</code>.
     */
    public VistaResumenGeneracionesRecord setTotalInversion(BigDecimal value) {
        set(10, value);
        return this;
    }

    /**
     * Getter for
     * <code>sistema_vehicular.vista_resumen_generaciones.total_inversion</code>.
     */
    public BigDecimal getTotalInversion() {
        return (BigDecimal) get(10);
    }

    /**
     * Setter for
     * <code>sistema_vehicular.vista_resumen_generaciones.total_ingresos</code>.
     */
    public VistaResumenGeneracionesRecord setTotalIngresos(BigDecimal value) {
        set(11, value);
        return this;
    }

    /**
     * Getter for
     * <code>sistema_vehicular.vista_resumen_generaciones.total_ingresos</code>.
     */
    public BigDecimal getTotalIngresos() {
        return (BigDecimal) get(11);
    }

    /**
     * Setter for
     * <code>sistema_vehicular.vista_resumen_generaciones.total_egresos</code>.
     */
    public VistaResumenGeneracionesRecord setTotalEgresos(BigDecimal value) {
        set(12, value);
        return this;
    }

    /**
     * Getter for
     * <code>sistema_vehicular.vista_resumen_generaciones.total_egresos</code>.
     */
    public BigDecimal getTotalEgresos() {
        return (BigDecimal) get(12);
    }

    /**
     * Setter for
     * <code>sistema_vehicular.vista_resumen_generaciones.balance_neto</code>.
     */
    public VistaResumenGeneracionesRecord setBalanceNeto(BigDecimal value) {
        set(13, value);
        return this;
    }

    /**
     * Getter for
     * <code>sistema_vehicular.vista_resumen_generaciones.balance_neto</code>.
     */
    public BigDecimal getBalanceNeto() {
        return (BigDecimal) get(13);
    }

    /**
     * Setter for
     * <code>sistema_vehicular.vista_resumen_generaciones.porcentaje_retorno</code>.
     */
    public VistaResumenGeneracionesRecord setPorcentajeRetorno(BigDecimal value) {
        set(14, value);
        return this;
    }

    /**
     * Getter for
     * <code>sistema_vehicular.vista_resumen_generaciones.porcentaje_retorno</code>.
     */
    public BigDecimal getPorcentajeRetorno() {
        return (BigDecimal) get(14);
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached VistaResumenGeneracionesRecord
     */
    public VistaResumenGeneracionesRecord() {
        super(VistaResumenGeneraciones.VISTA_RESUMEN_GENERACIONES);
    }

    /**
     * Create a detached, initialised VistaResumenGeneracionesRecord
     */
    public VistaResumenGeneracionesRecord(Integer generacionId, String marca, String modelo, String generacion, String descripcion, String claveGeneracion, Integer anioInicio, Integer anioFin, Long totalVehiculos, Long totalRepuestos, BigDecimal totalInversion, BigDecimal totalIngresos, BigDecimal totalEgresos, BigDecimal balanceNeto, BigDecimal porcentajeRetorno) {
        super(VistaResumenGeneraciones.VISTA_RESUMEN_GENERACIONES);

        setGeneracionId(generacionId);
        setMarca(marca);
        setModelo(modelo);
        setGeneracion(generacion);
        setDescripcion(descripcion);
        setClaveGeneracion(claveGeneracion);
        setAnioInicio(anioInicio);
        setAnioFin(anioFin);
        setTotalVehiculos(totalVehiculos);
        setTotalRepuestos(totalRepuestos);
        setTotalInversion(totalInversion);
        setTotalIngresos(totalIngresos);
        setTotalEgresos(totalEgresos);
        setBalanceNeto(balanceNeto);
        setPorcentajeRetorno(porcentajeRetorno);
        resetChangedOnNotNull();
    }

    /**
     * Create a detached, initialised VistaResumenGeneracionesRecord
     */
    public VistaResumenGeneracionesRecord(com.RodiejaContable.database.jooq.tables.pojos.VistaResumenGeneraciones value) {
        super(VistaResumenGeneraciones.VISTA_RESUMEN_GENERACIONES);

        if (value != null) {
            setGeneracionId(value.getGeneracionId());
            setMarca(value.getMarca());
            setModelo(value.getModelo());
            setGeneracion(value.getGeneracion());
            setDescripcion(value.getDescripcion());
            setClaveGeneracion(value.getClaveGeneracion());
            setAnioInicio(value.getAnioInicio());
            setAnioFin(value.getAnioFin());
            setTotalVehiculos(value.getTotalVehiculos());
            setTotalRepuestos(value.getTotalRepuestos());
            setTotalInversion(value.getTotalInversion());
            setTotalIngresos(value.getTotalIngresos());
            setTotalEgresos(value.getTotalEgresos());
            setBalanceNeto(value.getBalanceNeto());
            setPorcentajeRetorno(value.getPorcentajeRetorno());
            resetChangedOnNotNull();
        }
    }
}
