/*
 * This file is generated by jOOQ.
 */
package com.RodiejaContable.database.jooq.tables.records;


import com.RodiejaContable.database.jooq.tables.VistaRentabilidadGeneraciones;

import java.math.BigDecimal;

import org.jooq.impl.TableRecordImpl;


/**
 * VIEW
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class VistaRentabilidadGeneracionesRecord extends TableRecordImpl<VistaRentabilidadGeneracionesRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for
     * <code>sistema_vehicular.vista_rentabilidad_generaciones.generacion_id</code>.
     */
    public VistaRentabilidadGeneracionesRecord setGeneracionId(Integer value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for
     * <code>sistema_vehicular.vista_rentabilidad_generaciones.generacion_id</code>.
     */
    public Integer getGeneracionId() {
        return (Integer) get(0);
    }

    /**
     * Setter for
     * <code>sistema_vehicular.vista_rentabilidad_generaciones.generacion_completa</code>.
     */
    public VistaRentabilidadGeneracionesRecord setGeneracionCompleta(String value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for
     * <code>sistema_vehicular.vista_rentabilidad_generaciones.generacion_completa</code>.
     */
    public String getGeneracionCompleta() {
        return (String) get(1);
    }

    /**
     * Setter for
     * <code>sistema_vehicular.vista_rentabilidad_generaciones.anio_inicio</code>.
     */
    public VistaRentabilidadGeneracionesRecord setAnioInicio(Integer value) {
        set(2, value);
        return this;
    }

    /**
     * Getter for
     * <code>sistema_vehicular.vista_rentabilidad_generaciones.anio_inicio</code>.
     */
    public Integer getAnioInicio() {
        return (Integer) get(2);
    }

    /**
     * Setter for
     * <code>sistema_vehicular.vista_rentabilidad_generaciones.anio_fin</code>.
     */
    public VistaRentabilidadGeneracionesRecord setAnioFin(Integer value) {
        set(3, value);
        return this;
    }

    /**
     * Getter for
     * <code>sistema_vehicular.vista_rentabilidad_generaciones.anio_fin</code>.
     */
    public Integer getAnioFin() {
        return (Integer) get(3);
    }

    /**
     * Setter for
     * <code>sistema_vehicular.vista_rentabilidad_generaciones.total_vehiculos</code>.
     */
    public VistaRentabilidadGeneracionesRecord setTotalVehiculos(Long value) {
        set(4, value);
        return this;
    }

    /**
     * Getter for
     * <code>sistema_vehicular.vista_rentabilidad_generaciones.total_vehiculos</code>.
     */
    public Long getTotalVehiculos() {
        return (Long) get(4);
    }

    /**
     * Setter for
     * <code>sistema_vehicular.vista_rentabilidad_generaciones.vehiculos_vendidos</code>.
     */
    public VistaRentabilidadGeneracionesRecord setVehiculosVendidos(Long value) {
        set(5, value);
        return this;
    }

    /**
     * Getter for
     * <code>sistema_vehicular.vista_rentabilidad_generaciones.vehiculos_vendidos</code>.
     */
    public Long getVehiculosVendidos() {
        return (Long) get(5);
    }

    /**
     * Setter for
     * <code>sistema_vehicular.vista_rentabilidad_generaciones.vehiculos_disponibles</code>.
     */
    public VistaRentabilidadGeneracionesRecord setVehiculosDisponibles(Long value) {
        set(6, value);
        return this;
    }

    /**
     * Getter for
     * <code>sistema_vehicular.vista_rentabilidad_generaciones.vehiculos_disponibles</code>.
     */
    public Long getVehiculosDisponibles() {
        return (Long) get(6);
    }

    /**
     * Setter for
     * <code>sistema_vehicular.vista_rentabilidad_generaciones.total_inversion</code>.
     */
    public VistaRentabilidadGeneracionesRecord setTotalInversion(BigDecimal value) {
        set(7, value);
        return this;
    }

    /**
     * Getter for
     * <code>sistema_vehicular.vista_rentabilidad_generaciones.total_inversion</code>.
     */
    public BigDecimal getTotalInversion() {
        return (BigDecimal) get(7);
    }

    /**
     * Setter for
     * <code>sistema_vehicular.vista_rentabilidad_generaciones.total_ingresos</code>.
     */
    public VistaRentabilidadGeneracionesRecord setTotalIngresos(BigDecimal value) {
        set(8, value);
        return this;
    }

    /**
     * Getter for
     * <code>sistema_vehicular.vista_rentabilidad_generaciones.total_ingresos</code>.
     */
    public BigDecimal getTotalIngresos() {
        return (BigDecimal) get(8);
    }

    /**
     * Setter for
     * <code>sistema_vehicular.vista_rentabilidad_generaciones.total_egresos</code>.
     */
    public VistaRentabilidadGeneracionesRecord setTotalEgresos(BigDecimal value) {
        set(9, value);
        return this;
    }

    /**
     * Getter for
     * <code>sistema_vehicular.vista_rentabilidad_generaciones.total_egresos</code>.
     */
    public BigDecimal getTotalEgresos() {
        return (BigDecimal) get(9);
    }

    /**
     * Setter for
     * <code>sistema_vehicular.vista_rentabilidad_generaciones.balance_neto</code>.
     */
    public VistaRentabilidadGeneracionesRecord setBalanceNeto(BigDecimal value) {
        set(10, value);
        return this;
    }

    /**
     * Getter for
     * <code>sistema_vehicular.vista_rentabilidad_generaciones.balance_neto</code>.
     */
    public BigDecimal getBalanceNeto() {
        return (BigDecimal) get(10);
    }

    /**
     * Setter for
     * <code>sistema_vehicular.vista_rentabilidad_generaciones.roi_porcentaje</code>.
     */
    public VistaRentabilidadGeneracionesRecord setRoiPorcentaje(BigDecimal value) {
        set(11, value);
        return this;
    }

    /**
     * Getter for
     * <code>sistema_vehicular.vista_rentabilidad_generaciones.roi_porcentaje</code>.
     */
    public BigDecimal getRoiPorcentaje() {
        return (BigDecimal) get(11);
    }

    /**
     * Setter for
     * <code>sistema_vehicular.vista_rentabilidad_generaciones.utilidad_por_vehiculo</code>.
     */
    public VistaRentabilidadGeneracionesRecord setUtilidadPorVehiculo(BigDecimal value) {
        set(12, value);
        return this;
    }

    /**
     * Getter for
     * <code>sistema_vehicular.vista_rentabilidad_generaciones.utilidad_por_vehiculo</code>.
     */
    public BigDecimal getUtilidadPorVehiculo() {
        return (BigDecimal) get(12);
    }

    /**
     * Setter for
     * <code>sistema_vehicular.vista_rentabilidad_generaciones.multiplicador_inversion</code>.
     */
    public VistaRentabilidadGeneracionesRecord setMultiplicadorInversion(BigDecimal value) {
        set(13, value);
        return this;
    }

    /**
     * Getter for
     * <code>sistema_vehicular.vista_rentabilidad_generaciones.multiplicador_inversion</code>.
     */
    public BigDecimal getMultiplicadorInversion() {
        return (BigDecimal) get(13);
    }

    /**
     * Setter for
     * <code>sistema_vehicular.vista_rentabilidad_generaciones.clasificacion_rentabilidad</code>.
     */
    public VistaRentabilidadGeneracionesRecord setClasificacionRentabilidad(String value) {
        set(14, value);
        return this;
    }

    /**
     * Getter for
     * <code>sistema_vehicular.vista_rentabilidad_generaciones.clasificacion_rentabilidad</code>.
     */
    public String getClasificacionRentabilidad() {
        return (String) get(14);
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached VistaRentabilidadGeneracionesRecord
     */
    public VistaRentabilidadGeneracionesRecord() {
        super(VistaRentabilidadGeneraciones.VISTA_RENTABILIDAD_GENERACIONES);
    }

    /**
     * Create a detached, initialised VistaRentabilidadGeneracionesRecord
     */
    public VistaRentabilidadGeneracionesRecord(Integer generacionId, String generacionCompleta, Integer anioInicio, Integer anioFin, Long totalVehiculos, Long vehiculosVendidos, Long vehiculosDisponibles, BigDecimal totalInversion, BigDecimal totalIngresos, BigDecimal totalEgresos, BigDecimal balanceNeto, BigDecimal roiPorcentaje, BigDecimal utilidadPorVehiculo, BigDecimal multiplicadorInversion, String clasificacionRentabilidad) {
        super(VistaRentabilidadGeneraciones.VISTA_RENTABILIDAD_GENERACIONES);

        setGeneracionId(generacionId);
        setGeneracionCompleta(generacionCompleta);
        setAnioInicio(anioInicio);
        setAnioFin(anioFin);
        setTotalVehiculos(totalVehiculos);
        setVehiculosVendidos(vehiculosVendidos);
        setVehiculosDisponibles(vehiculosDisponibles);
        setTotalInversion(totalInversion);
        setTotalIngresos(totalIngresos);
        setTotalEgresos(totalEgresos);
        setBalanceNeto(balanceNeto);
        setRoiPorcentaje(roiPorcentaje);
        setUtilidadPorVehiculo(utilidadPorVehiculo);
        setMultiplicadorInversion(multiplicadorInversion);
        setClasificacionRentabilidad(clasificacionRentabilidad);
        resetChangedOnNotNull();
    }

    /**
     * Create a detached, initialised VistaRentabilidadGeneracionesRecord
     */
    public VistaRentabilidadGeneracionesRecord(com.RodiejaContable.database.jooq.tables.pojos.VistaRentabilidadGeneraciones value) {
        super(VistaRentabilidadGeneraciones.VISTA_RENTABILIDAD_GENERACIONES);

        if (value != null) {
            setGeneracionId(value.getGeneracionId());
            setGeneracionCompleta(value.getGeneracionCompleta());
            setAnioInicio(value.getAnioInicio());
            setAnioFin(value.getAnioFin());
            setTotalVehiculos(value.getTotalVehiculos());
            setVehiculosVendidos(value.getVehiculosVendidos());
            setVehiculosDisponibles(value.getVehiculosDisponibles());
            setTotalInversion(value.getTotalInversion());
            setTotalIngresos(value.getTotalIngresos());
            setTotalEgresos(value.getTotalEgresos());
            setBalanceNeto(value.getBalanceNeto());
            setRoiPorcentaje(value.getRoiPorcentaje());
            setUtilidadPorVehiculo(value.getUtilidadPorVehiculo());
            setMultiplicadorInversion(value.getMultiplicadorInversion());
            setClasificacionRentabilidad(value.getClasificacionRentabilidad());
            resetChangedOnNotNull();
        }
    }
}
