/*
 * This file is generated by jOOQ.
 */
package com.RodiejaContable.database.jooq.tables.records;


import com.RodiejaContable.database.jooq.enums.VistaTransaccionesCompletasCategoria;
import com.RodiejaContable.database.jooq.enums.VistaTransaccionesCompletasEstado;
import com.RodiejaContable.database.jooq.tables.VistaTransaccionesCompletas;

import java.math.BigDecimal;
import java.time.LocalDate;

import org.jooq.impl.TableRecordImpl;


/**
 * VIEW
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class VistaTransaccionesCompletasRecord extends TableRecordImpl<VistaTransaccionesCompletasRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for
     * <code>sistema_vehicular.vista_transacciones_completas.id</code>.
     */
    public VistaTransaccionesCompletasRecord setId(Integer value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for
     * <code>sistema_vehicular.vista_transacciones_completas.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for
     * <code>sistema_vehicular.vista_transacciones_completas.codigo_transaccion</code>.
     */
    public VistaTransaccionesCompletasRecord setCodigoTransaccion(String value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for
     * <code>sistema_vehicular.vista_transacciones_completas.codigo_transaccion</code>.
     */
    public String getCodigoTransaccion() {
        return (String) get(1);
    }

    /**
     * Setter for
     * <code>sistema_vehicular.vista_transacciones_completas.fecha</code>.
     */
    public VistaTransaccionesCompletasRecord setFecha(LocalDate value) {
        set(2, value);
        return this;
    }

    /**
     * Getter for
     * <code>sistema_vehicular.vista_transacciones_completas.fecha</code>.
     */
    public LocalDate getFecha() {
        return (LocalDate) get(2);
    }

    /**
     * Setter for
     * <code>sistema_vehicular.vista_transacciones_completas.monto</code>.
     */
    public VistaTransaccionesCompletasRecord setMonto(BigDecimal value) {
        set(3, value);
        return this;
    }

    /**
     * Getter for
     * <code>sistema_vehicular.vista_transacciones_completas.monto</code>.
     */
    public BigDecimal getMonto() {
        return (BigDecimal) get(3);
    }

    /**
     * Setter for
     * <code>sistema_vehicular.vista_transacciones_completas.comision_empleado</code>.
     */
    public VistaTransaccionesCompletasRecord setComisionEmpleado(BigDecimal value) {
        set(4, value);
        return this;
    }

    /**
     * Getter for
     * <code>sistema_vehicular.vista_transacciones_completas.comision_empleado</code>.
     */
    public BigDecimal getComisionEmpleado() {
        return (BigDecimal) get(4);
    }

    /**
     * Setter for
     * <code>sistema_vehicular.vista_transacciones_completas.descripcion</code>.
     */
    public VistaTransaccionesCompletasRecord setDescripcion(String value) {
        set(5, value);
        return this;
    }

    /**
     * Getter for
     * <code>sistema_vehicular.vista_transacciones_completas.descripcion</code>.
     */
    public String getDescripcion() {
        return (String) get(5);
    }

    /**
     * Setter for
     * <code>sistema_vehicular.vista_transacciones_completas.referencia</code>.
     */
    public VistaTransaccionesCompletasRecord setReferencia(String value) {
        set(6, value);
        return this;
    }

    /**
     * Getter for
     * <code>sistema_vehicular.vista_transacciones_completas.referencia</code>.
     */
    public String getReferencia() {
        return (String) get(6);
    }

    /**
     * Setter for
     * <code>sistema_vehicular.vista_transacciones_completas.estado</code>.
     */
    public VistaTransaccionesCompletasRecord setEstado(VistaTransaccionesCompletasEstado value) {
        set(7, value);
        return this;
    }

    /**
     * Getter for
     * <code>sistema_vehicular.vista_transacciones_completas.estado</code>.
     */
    public VistaTransaccionesCompletasEstado getEstado() {
        return (VistaTransaccionesCompletasEstado) get(7);
    }

    /**
     * Setter for
     * <code>sistema_vehicular.vista_transacciones_completas.tipo_transaccion</code>.
     */
    public VistaTransaccionesCompletasRecord setTipoTransaccion(String value) {
        set(8, value);
        return this;
    }

    /**
     * Getter for
     * <code>sistema_vehicular.vista_transacciones_completas.tipo_transaccion</code>.
     */
    public String getTipoTransaccion() {
        return (String) get(8);
    }

    /**
     * Setter for
     * <code>sistema_vehicular.vista_transacciones_completas.categoria</code>.
     */
    public VistaTransaccionesCompletasRecord setCategoria(VistaTransaccionesCompletasCategoria value) {
        set(9, value);
        return this;
    }

    /**
     * Getter for
     * <code>sistema_vehicular.vista_transacciones_completas.categoria</code>.
     */
    public VistaTransaccionesCompletasCategoria getCategoria() {
        return (VistaTransaccionesCompletasCategoria) get(9);
    }

    /**
     * Setter for
     * <code>sistema_vehicular.vista_transacciones_completas.empleado</code>.
     */
    public VistaTransaccionesCompletasRecord setEmpleado(String value) {
        set(10, value);
        return this;
    }

    /**
     * Getter for
     * <code>sistema_vehicular.vista_transacciones_completas.empleado</code>.
     */
    public String getEmpleado() {
        return (String) get(10);
    }

    /**
     * Setter for
     * <code>sistema_vehicular.vista_transacciones_completas.codigo_vehiculo</code>.
     */
    public VistaTransaccionesCompletasRecord setCodigoVehiculo(String value) {
        set(11, value);
        return this;
    }

    /**
     * Getter for
     * <code>sistema_vehicular.vista_transacciones_completas.codigo_vehiculo</code>.
     */
    public String getCodigoVehiculo() {
        return (String) get(11);
    }

    /**
     * Setter for
     * <code>sistema_vehicular.vista_transacciones_completas.codigo_repuesto</code>.
     */
    public VistaTransaccionesCompletasRecord setCodigoRepuesto(String value) {
        set(12, value);
        return this;
    }

    /**
     * Getter for
     * <code>sistema_vehicular.vista_transacciones_completas.codigo_repuesto</code>.
     */
    public String getCodigoRepuesto() {
        return (String) get(12);
    }

    /**
     * Setter for
     * <code>sistema_vehicular.vista_transacciones_completas.marca</code>.
     */
    public VistaTransaccionesCompletasRecord setMarca(String value) {
        set(13, value);
        return this;
    }

    /**
     * Getter for
     * <code>sistema_vehicular.vista_transacciones_completas.marca</code>.
     */
    public String getMarca() {
        return (String) get(13);
    }

    /**
     * Setter for
     * <code>sistema_vehicular.vista_transacciones_completas.modelo</code>.
     */
    public VistaTransaccionesCompletasRecord setModelo(String value) {
        set(14, value);
        return this;
    }

    /**
     * Getter for
     * <code>sistema_vehicular.vista_transacciones_completas.modelo</code>.
     */
    public String getModelo() {
        return (String) get(14);
    }

    /**
     * Setter for
     * <code>sistema_vehicular.vista_transacciones_completas.generacion</code>.
     */
    public VistaTransaccionesCompletasRecord setGeneracion(String value) {
        set(15, value);
        return this;
    }

    /**
     * Getter for
     * <code>sistema_vehicular.vista_transacciones_completas.generacion</code>.
     */
    public String getGeneracion() {
        return (String) get(15);
    }

    /**
     * Setter for
     * <code>sistema_vehicular.vista_transacciones_completas.clave_generacion</code>.
     */
    public VistaTransaccionesCompletasRecord setClaveGeneracion(String value) {
        set(16, value);
        return this;
    }

    /**
     * Getter for
     * <code>sistema_vehicular.vista_transacciones_completas.clave_generacion</code>.
     */
    public String getClaveGeneracion() {
        return (String) get(16);
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached VistaTransaccionesCompletasRecord
     */
    public VistaTransaccionesCompletasRecord() {
        super(VistaTransaccionesCompletas.VISTA_TRANSACCIONES_COMPLETAS);
    }

    /**
     * Create a detached, initialised VistaTransaccionesCompletasRecord
     */
    public VistaTransaccionesCompletasRecord(Integer id, String codigoTransaccion, LocalDate fecha, BigDecimal monto, BigDecimal comisionEmpleado, String descripcion, String referencia, VistaTransaccionesCompletasEstado estado, String tipoTransaccion, VistaTransaccionesCompletasCategoria categoria, String empleado, String codigoVehiculo, String codigoRepuesto, String marca, String modelo, String generacion, String claveGeneracion) {
        super(VistaTransaccionesCompletas.VISTA_TRANSACCIONES_COMPLETAS);

        setId(id);
        setCodigoTransaccion(codigoTransaccion);
        setFecha(fecha);
        setMonto(monto);
        setComisionEmpleado(comisionEmpleado);
        setDescripcion(descripcion);
        setReferencia(referencia);
        setEstado(estado);
        setTipoTransaccion(tipoTransaccion);
        setCategoria(categoria);
        setEmpleado(empleado);
        setCodigoVehiculo(codigoVehiculo);
        setCodigoRepuesto(codigoRepuesto);
        setMarca(marca);
        setModelo(modelo);
        setGeneracion(generacion);
        setClaveGeneracion(claveGeneracion);
        resetChangedOnNotNull();
    }

    /**
     * Create a detached, initialised VistaTransaccionesCompletasRecord
     */
    public VistaTransaccionesCompletasRecord(com.RodiejaContable.database.jooq.tables.pojos.VistaTransaccionesCompletas value) {
        super(VistaTransaccionesCompletas.VISTA_TRANSACCIONES_COMPLETAS);

        if (value != null) {
            setId(value.getId());
            setCodigoTransaccion(value.getCodigoTransaccion());
            setFecha(value.getFecha());
            setMonto(value.getMonto());
            setComisionEmpleado(value.getComisionEmpleado());
            setDescripcion(value.getDescripcion());
            setReferencia(value.getReferencia());
            setEstado(value.getEstado());
            setTipoTransaccion(value.getTipoTransaccion());
            setCategoria(value.getCategoria());
            setEmpleado(value.getEmpleado());
            setCodigoVehiculo(value.getCodigoVehiculo());
            setCodigoRepuesto(value.getCodigoRepuesto());
            setMarca(value.getMarca());
            setModelo(value.getModelo());
            setGeneracion(value.getGeneracion());
            setClaveGeneracion(value.getClaveGeneracion());
            resetChangedOnNotNull();
        }
    }
}
