/*
 * This file is generated by jOOQ.
 */
package com.RodiejaContable.database.jooq.tables.records;


import com.RodiejaContable.database.jooq.tables.VistaTopProductosVendidos;

import java.math.BigDecimal;

import org.jooq.impl.TableRecordImpl;


/**
 * VIEW
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class VistaTopProductosVendidosRecord extends TableRecordImpl<VistaTopProductosVendidosRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for
     * <code>sistema_vehicular.vista_top_productos_vendidos.tipo_producto</code>.
     */
    public VistaTopProductosVendidosRecord setTipoProducto(String value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for
     * <code>sistema_vehicular.vista_top_productos_vendidos.tipo_producto</code>.
     */
    public String getTipoProducto() {
        return (String) get(0);
    }

    /**
     * Setter for
     * <code>sistema_vehicular.vista_top_productos_vendidos.producto</code>.
     */
    public VistaTopProductosVendidosRecord setProducto(String value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for
     * <code>sistema_vehicular.vista_top_productos_vendidos.producto</code>.
     */
    public String getProducto() {
        return (String) get(1);
    }

    /**
     * Setter for
     * <code>sistema_vehicular.vista_top_productos_vendidos.veces_vendido</code>.
     */
    public VistaTopProductosVendidosRecord setVecesVendido(Long value) {
        set(2, value);
        return this;
    }

    /**
     * Getter for
     * <code>sistema_vehicular.vista_top_productos_vendidos.veces_vendido</code>.
     */
    public Long getVecesVendido() {
        return (Long) get(2);
    }

    /**
     * Setter for
     * <code>sistema_vehicular.vista_top_productos_vendidos.total_ingresos</code>.
     */
    public VistaTopProductosVendidosRecord setTotalIngresos(BigDecimal value) {
        set(3, value);
        return this;
    }

    /**
     * Getter for
     * <code>sistema_vehicular.vista_top_productos_vendidos.total_ingresos</code>.
     */
    public BigDecimal getTotalIngresos() {
        return (BigDecimal) get(3);
    }

    /**
     * Setter for
     * <code>sistema_vehicular.vista_top_productos_vendidos.promedio_venta</code>.
     */
    public VistaTopProductosVendidosRecord setPromedioVenta(BigDecimal value) {
        set(4, value);
        return this;
    }

    /**
     * Getter for
     * <code>sistema_vehicular.vista_top_productos_vendidos.promedio_venta</code>.
     */
    public BigDecimal getPromedioVenta() {
        return (BigDecimal) get(4);
    }

    /**
     * Setter for
     * <code>sistema_vehicular.vista_top_productos_vendidos.total_comisiones</code>.
     */
    public VistaTopProductosVendidosRecord setTotalComisiones(BigDecimal value) {
        set(5, value);
        return this;
    }

    /**
     * Getter for
     * <code>sistema_vehicular.vista_top_productos_vendidos.total_comisiones</code>.
     */
    public BigDecimal getTotalComisiones() {
        return (BigDecimal) get(5);
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached VistaTopProductosVendidosRecord
     */
    public VistaTopProductosVendidosRecord() {
        super(VistaTopProductosVendidos.VISTA_TOP_PRODUCTOS_VENDIDOS);
    }

    /**
     * Create a detached, initialised VistaTopProductosVendidosRecord
     */
    public VistaTopProductosVendidosRecord(String tipoProducto, String producto, Long vecesVendido, BigDecimal totalIngresos, BigDecimal promedioVenta, BigDecimal totalComisiones) {
        super(VistaTopProductosVendidos.VISTA_TOP_PRODUCTOS_VENDIDOS);

        setTipoProducto(tipoProducto);
        setProducto(producto);
        setVecesVendido(vecesVendido);
        setTotalIngresos(totalIngresos);
        setPromedioVenta(promedioVenta);
        setTotalComisiones(totalComisiones);
        resetChangedOnNotNull();
    }

    /**
     * Create a detached, initialised VistaTopProductosVendidosRecord
     */
    public VistaTopProductosVendidosRecord(com.RodiejaContable.database.jooq.tables.pojos.VistaTopProductosVendidos value) {
        super(VistaTopProductosVendidos.VISTA_TOP_PRODUCTOS_VENDIDOS);

        if (value != null) {
            setTipoProducto(value.getTipoProducto());
            setProducto(value.getProducto());
            setVecesVendido(value.getVecesVendido());
            setTotalIngresos(value.getTotalIngresos());
            setPromedioVenta(value.getPromedioVenta());
            setTotalComisiones(value.getTotalComisiones());
            resetChangedOnNotNull();
        }
    }
}
