/*
 * This file is generated by jOOQ.
 */
package com.RodiejaContable.database.jooq.tables;


import com.RodiejaContable.database.jooq.Indexes;
import com.RodiejaContable.database.jooq.Keys;
import com.RodiejaContable.database.jooq.SistemaVehicular;
import com.RodiejaContable.database.jooq.enums.HistorialRepuestosAccion;
import com.RodiejaContable.database.jooq.tables.InventarioRepuestos.InventarioRepuestosPath;
import com.RodiejaContable.database.jooq.tables.records.HistorialRepuestosRecord;

import java.time.LocalDateTime;
import java.util.Arrays;
import java.util.Collection;
import java.util.List;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.Index;
import org.jooq.InverseForeignKey;
import org.jooq.Name;
import org.jooq.Path;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.Record;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class HistorialRepuestos extends TableImpl<HistorialRepuestosRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of
     * <code>sistema_vehicular.historial_repuestos</code>
     */
    public static final HistorialRepuestos HISTORIAL_REPUESTOS = new HistorialRepuestos();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<HistorialRepuestosRecord> getRecordType() {
        return HistorialRepuestosRecord.class;
    }

    /**
     * The column <code>sistema_vehicular.historial_repuestos.id</code>.
     */
    public final TableField<HistorialRepuestosRecord, Integer> ID = createField(DSL.name("id"), SQLDataType.INTEGER.nullable(false).identity(true), this, "");

    /**
     * The column
     * <code>sistema_vehicular.historial_repuestos.repuesto_id</code>.
     */
    public final TableField<HistorialRepuestosRecord, Integer> REPUESTO_ID = createField(DSL.name("repuesto_id"), SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>sistema_vehicular.historial_repuestos.accion</code>.
     */
    public final TableField<HistorialRepuestosRecord, HistorialRepuestosAccion> ACCION = createField(DSL.name("accion"), SQLDataType.VARCHAR(6).nullable(false).asEnumDataType(HistorialRepuestosAccion.class), this, "");

    /**
     * The column
     * <code>sistema_vehicular.historial_repuestos.campo_modificado</code>.
     */
    public final TableField<HistorialRepuestosRecord, String> CAMPO_MODIFICADO = createField(DSL.name("campo_modificado"), SQLDataType.VARCHAR(50).defaultValue(DSL.inline("NULL", SQLDataType.VARCHAR)), this, "");

    /**
     * The column
     * <code>sistema_vehicular.historial_repuestos.valor_anterior</code>.
     */
    public final TableField<HistorialRepuestosRecord, String> VALOR_ANTERIOR = createField(DSL.name("valor_anterior"), SQLDataType.CLOB.defaultValue(DSL.inline("NULL", SQLDataType.CLOB)), this, "");

    /**
     * The column
     * <code>sistema_vehicular.historial_repuestos.valor_nuevo</code>.
     */
    public final TableField<HistorialRepuestosRecord, String> VALOR_NUEVO = createField(DSL.name("valor_nuevo"), SQLDataType.CLOB.defaultValue(DSL.inline("NULL", SQLDataType.CLOB)), this, "");

    /**
     * The column <code>sistema_vehicular.historial_repuestos.usuario</code>.
     */
    public final TableField<HistorialRepuestosRecord, String> USUARIO = createField(DSL.name("usuario"), SQLDataType.VARCHAR(100).defaultValue(DSL.inline("NULL", SQLDataType.VARCHAR)), this, "");

    /**
     * The column
     * <code>sistema_vehicular.historial_repuestos.fecha_cambio</code>.
     */
    public final TableField<HistorialRepuestosRecord, LocalDateTime> FECHA_CAMBIO = createField(DSL.name("fecha_cambio"), SQLDataType.LOCALDATETIME(0).defaultValue(DSL.field(DSL.raw("current_timestamp()"), SQLDataType.LOCALDATETIME)), this, "");

    /**
     * The column <code>sistema_vehicular.historial_repuestos.ip_usuario</code>.
     */
    public final TableField<HistorialRepuestosRecord, String> IP_USUARIO = createField(DSL.name("ip_usuario"), SQLDataType.VARCHAR(45).defaultValue(DSL.inline("NULL", SQLDataType.VARCHAR)), this, "");

    /**
     * The column
     * <code>sistema_vehicular.historial_repuestos.observaciones</code>.
     */
    public final TableField<HistorialRepuestosRecord, String> OBSERVACIONES = createField(DSL.name("observaciones"), SQLDataType.CLOB.defaultValue(DSL.inline("NULL", SQLDataType.CLOB)), this, "");

    private HistorialRepuestos(Name alias, Table<HistorialRepuestosRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private HistorialRepuestos(Name alias, Table<HistorialRepuestosRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>sistema_vehicular.historial_repuestos</code>
     * table reference
     */
    public HistorialRepuestos(String alias) {
        this(DSL.name(alias), HISTORIAL_REPUESTOS);
    }

    /**
     * Create an aliased <code>sistema_vehicular.historial_repuestos</code>
     * table reference
     */
    public HistorialRepuestos(Name alias) {
        this(alias, HISTORIAL_REPUESTOS);
    }

    /**
     * Create a <code>sistema_vehicular.historial_repuestos</code> table
     * reference
     */
    public HistorialRepuestos() {
        this(DSL.name("historial_repuestos"), null);
    }

    public <O extends Record> HistorialRepuestos(Table<O> path, ForeignKey<O, HistorialRepuestosRecord> childPath, InverseForeignKey<O, HistorialRepuestosRecord> parentPath) {
        super(path, childPath, parentPath, HISTORIAL_REPUESTOS);
    }

    /**
     * A subtype implementing {@link Path} for simplified path-based joins.
     */
    public static class HistorialRepuestosPath extends HistorialRepuestos implements Path<HistorialRepuestosRecord> {
        public <O extends Record> HistorialRepuestosPath(Table<O> path, ForeignKey<O, HistorialRepuestosRecord> childPath, InverseForeignKey<O, HistorialRepuestosRecord> parentPath) {
            super(path, childPath, parentPath);
        }
        private HistorialRepuestosPath(Name alias, Table<HistorialRepuestosRecord> aliased) {
            super(alias, aliased);
        }

        @Override
        public HistorialRepuestosPath as(String alias) {
            return new HistorialRepuestosPath(DSL.name(alias), this);
        }

        @Override
        public HistorialRepuestosPath as(Name alias) {
            return new HistorialRepuestosPath(alias, this);
        }

        @Override
        public HistorialRepuestosPath as(Table<?> alias) {
            return new HistorialRepuestosPath(alias.getQualifiedName(), this);
        }
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : SistemaVehicular.SISTEMA_VEHICULAR;
    }

    @Override
    public List<Index> getIndexes() {
        return Arrays.asList(Indexes.HISTORIAL_REPUESTOS_IDX_ACCION, Indexes.HISTORIAL_REPUESTOS_IDX_REPUESTO_FECHA);
    }

    @Override
    public Identity<HistorialRepuestosRecord, Integer> getIdentity() {
        return (Identity<HistorialRepuestosRecord, Integer>) super.getIdentity();
    }

    @Override
    public UniqueKey<HistorialRepuestosRecord> getPrimaryKey() {
        return Keys.KEY_HISTORIAL_REPUESTOS_PRIMARY;
    }

    @Override
    public List<ForeignKey<HistorialRepuestosRecord, ?>> getReferences() {
        return Arrays.asList(Keys.HISTORIAL_REPUESTOS_IBFK_1);
    }

    private transient InventarioRepuestosPath _inventarioRepuestos;

    /**
     * Get the implicit join path to the
     * <code>sistema_vehicular.inventario_repuestos</code> table.
     */
    public InventarioRepuestosPath inventarioRepuestos() {
        if (_inventarioRepuestos == null)
            _inventarioRepuestos = new InventarioRepuestosPath(this, Keys.HISTORIAL_REPUESTOS_IBFK_1, null);

        return _inventarioRepuestos;
    }

    @Override
    public HistorialRepuestos as(String alias) {
        return new HistorialRepuestos(DSL.name(alias), this);
    }

    @Override
    public HistorialRepuestos as(Name alias) {
        return new HistorialRepuestos(alias, this);
    }

    @Override
    public HistorialRepuestos as(Table<?> alias) {
        return new HistorialRepuestos(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public HistorialRepuestos rename(String name) {
        return new HistorialRepuestos(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public HistorialRepuestos rename(Name name) {
        return new HistorialRepuestos(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public HistorialRepuestos rename(Table<?> name) {
        return new HistorialRepuestos(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public HistorialRepuestos where(Condition condition) {
        return new HistorialRepuestos(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public HistorialRepuestos where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public HistorialRepuestos where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public HistorialRepuestos where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public HistorialRepuestos where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public HistorialRepuestos where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public HistorialRepuestos where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public HistorialRepuestos where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public HistorialRepuestos whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public HistorialRepuestos whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
