/*
 * This file is generated by jOOQ.
 */
package com.RodiejaContable.database.jooq.tables;


import com.RodiejaContable.database.jooq.SistemaVehicular;
import com.RodiejaContable.database.jooq.tables.records.VistaDashboardEjecutivoRecord;

import java.math.BigDecimal;
import java.util.Collection;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.Name;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * VIEW
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class VistaDashboardEjecutivo extends TableImpl<VistaDashboardEjecutivoRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of
     * <code>sistema_vehicular.vista_dashboard_ejecutivo</code>
     */
    public static final VistaDashboardEjecutivo VISTA_DASHBOARD_EJECUTIVO = new VistaDashboardEjecutivo();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<VistaDashboardEjecutivoRecord> getRecordType() {
        return VistaDashboardEjecutivoRecord.class;
    }

    /**
     * The column
     * <code>sistema_vehicular.vista_dashboard_ejecutivo.seccion</code>.
     */
    public final TableField<VistaDashboardEjecutivoRecord, String> SECCION = createField(DSL.name("seccion"), SQLDataType.VARCHAR(15).nullable(false).defaultValue(DSL.inline("''", SQLDataType.VARCHAR)), this, "");

    /**
     * The column
     * <code>sistema_vehicular.vista_dashboard_ejecutivo.total_vehiculos</code>.
     */
    public final TableField<VistaDashboardEjecutivoRecord, Long> TOTAL_VEHICULOS = createField(DSL.name("total_vehiculos"), SQLDataType.BIGINT.nullable(false).defaultValue(DSL.inline("0", SQLDataType.BIGINT)), this, "");

    /**
     * The column
     * <code>sistema_vehicular.vista_dashboard_ejecutivo.vehiculos_disponibles</code>.
     */
    public final TableField<VistaDashboardEjecutivoRecord, Long> VEHICULOS_DISPONIBLES = createField(DSL.name("vehiculos_disponibles"), SQLDataType.BIGINT.nullable(false).defaultValue(DSL.inline("0", SQLDataType.BIGINT)), this, "");

    /**
     * The column
     * <code>sistema_vehicular.vista_dashboard_ejecutivo.vehiculos_vendidos</code>.
     */
    public final TableField<VistaDashboardEjecutivoRecord, Long> VEHICULOS_VENDIDOS = createField(DSL.name("vehiculos_vendidos"), SQLDataType.BIGINT.nullable(false).defaultValue(DSL.inline("0", SQLDataType.BIGINT)), this, "");

    /**
     * The column
     * <code>sistema_vehicular.vista_dashboard_ejecutivo.total_repuestos</code>.
     */
    public final TableField<VistaDashboardEjecutivoRecord, Long> TOTAL_REPUESTOS = createField(DSL.name("total_repuestos"), SQLDataType.BIGINT.nullable(false).defaultValue(DSL.inline("0", SQLDataType.BIGINT)), this, "");

    /**
     * The column
     * <code>sistema_vehicular.vista_dashboard_ejecutivo.repuestos_stock</code>.
     */
    public final TableField<VistaDashboardEjecutivoRecord, Long> REPUESTOS_STOCK = createField(DSL.name("repuestos_stock"), SQLDataType.BIGINT.nullable(false).defaultValue(DSL.inline("0", SQLDataType.BIGINT)), this, "");

    /**
     * The column
     * <code>sistema_vehicular.vista_dashboard_ejecutivo.inversion_total</code>.
     */
    public final TableField<VistaDashboardEjecutivoRecord, BigDecimal> INVERSION_TOTAL = createField(DSL.name("inversion_total"), SQLDataType.DECIMAL(37, 2).defaultValue(DSL.inline("NULL", SQLDataType.DECIMAL)), this, "");

    /**
     * The column
     * <code>sistema_vehicular.vista_dashboard_ejecutivo.ingresos_totales</code>.
     */
    public final TableField<VistaDashboardEjecutivoRecord, BigDecimal> INGRESOS_TOTALES = createField(DSL.name("ingresos_totales"), SQLDataType.DECIMAL(37, 2).defaultValue(DSL.inline("NULL", SQLDataType.DECIMAL)), this, "");

    /**
     * The column
     * <code>sistema_vehicular.vista_dashboard_ejecutivo.egresos_totales</code>.
     */
    public final TableField<VistaDashboardEjecutivoRecord, BigDecimal> EGRESOS_TOTALES = createField(DSL.name("egresos_totales"), SQLDataType.DECIMAL(37, 2).defaultValue(DSL.inline("NULL", SQLDataType.DECIMAL)), this, "");

    /**
     * The column
     * <code>sistema_vehicular.vista_dashboard_ejecutivo.balance_neto_total</code>.
     */
    public final TableField<VistaDashboardEjecutivoRecord, BigDecimal> BALANCE_NETO_TOTAL = createField(DSL.name("balance_neto_total"), SQLDataType.DECIMAL(37, 2).defaultValue(DSL.inline("NULL", SQLDataType.DECIMAL)), this, "");

    /**
     * The column
     * <code>sistema_vehicular.vista_dashboard_ejecutivo.roi_promedio</code>.
     */
    public final TableField<VistaDashboardEjecutivoRecord, BigDecimal> ROI_PROMEDIO = createField(DSL.name("roi_promedio"), SQLDataType.DECIMAL(21, 2).defaultValue(DSL.inline("NULL", SQLDataType.DECIMAL)), this, "");

    private VistaDashboardEjecutivo(Name alias, Table<VistaDashboardEjecutivoRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private VistaDashboardEjecutivo(Name alias, Table<VistaDashboardEjecutivoRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment("VIEW"), TableOptions.view("create view `vista_dashboard_ejecutivo` as select 'Resumen General' AS `seccion`,count(distinct `v`.`id`) AS `total_vehiculos`,count(distinct case when `v`.`estado` = 'DISPONIBLE' then `v`.`id` end) AS `vehiculos_disponibles`,count(distinct case when `v`.`estado` = 'VENDIDO' then `v`.`id` end) AS `vehiculos_vendidos`,count(distinct `ir`.`id`) AS `total_repuestos`,count(distinct case when `ir`.`estado` = 'STOCK' then `ir`.`id` end) AS `repuestos_stock`,sum(distinct `g`.`total_inversion`) AS `inversion_total`,sum(distinct `g`.`total_ingresos`) AS `ingresos_totales`,sum(distinct `g`.`total_egresos`) AS `egresos_totales`,sum(distinct `g`.`balance_neto`) AS `balance_neto_total`,round(avg(case when `g`.`total_inversion` > 0 then `g`.`balance_neto` / `g`.`total_inversion` * 100 end),2) AS `roi_promedio` from ((`sistema_vehicular`.`vehiculos` `v` left join `sistema_vehicular`.`generaciones` `g` on(`v`.`generacion_id` = `g`.`id`)) left join `sistema_vehicular`.`inventario_repuestos` `ir` on(`v`.`id` = `ir`.`vehiculo_origen_id`)) where `v`.`activo` = 1 and `g`.`activo` = 1"), where);
    }

    /**
     * Create an aliased
     * <code>sistema_vehicular.vista_dashboard_ejecutivo</code> table reference
     */
    public VistaDashboardEjecutivo(String alias) {
        this(DSL.name(alias), VISTA_DASHBOARD_EJECUTIVO);
    }

    /**
     * Create an aliased
     * <code>sistema_vehicular.vista_dashboard_ejecutivo</code> table reference
     */
    public VistaDashboardEjecutivo(Name alias) {
        this(alias, VISTA_DASHBOARD_EJECUTIVO);
    }

    /**
     * Create a <code>sistema_vehicular.vista_dashboard_ejecutivo</code> table
     * reference
     */
    public VistaDashboardEjecutivo() {
        this(DSL.name("vista_dashboard_ejecutivo"), null);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : SistemaVehicular.SISTEMA_VEHICULAR;
    }

    @Override
    public VistaDashboardEjecutivo as(String alias) {
        return new VistaDashboardEjecutivo(DSL.name(alias), this);
    }

    @Override
    public VistaDashboardEjecutivo as(Name alias) {
        return new VistaDashboardEjecutivo(alias, this);
    }

    @Override
    public VistaDashboardEjecutivo as(Table<?> alias) {
        return new VistaDashboardEjecutivo(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public VistaDashboardEjecutivo rename(String name) {
        return new VistaDashboardEjecutivo(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public VistaDashboardEjecutivo rename(Name name) {
        return new VistaDashboardEjecutivo(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public VistaDashboardEjecutivo rename(Table<?> name) {
        return new VistaDashboardEjecutivo(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public VistaDashboardEjecutivo where(Condition condition) {
        return new VistaDashboardEjecutivo(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public VistaDashboardEjecutivo where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public VistaDashboardEjecutivo where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public VistaDashboardEjecutivo where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public VistaDashboardEjecutivo where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public VistaDashboardEjecutivo where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public VistaDashboardEjecutivo where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public VistaDashboardEjecutivo where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public VistaDashboardEjecutivo whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public VistaDashboardEjecutivo whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
