/*
 * This file is generated by jOOQ.
 */
package com.RodiejaContable.database.jooq.tables;


import com.RodiejaContable.database.jooq.SistemaVehicular;
import com.RodiejaContable.database.jooq.enums.VistaInventarioCompletoEstado;
import com.RodiejaContable.database.jooq.enums.VistaInventarioCompletoParteVehiculo;
import com.RodiejaContable.database.jooq.tables.records.VistaInventarioCompletoRecord;

import java.math.BigDecimal;
import java.util.Collection;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.Name;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * VIEW
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class VistaInventarioCompleto extends TableImpl<VistaInventarioCompletoRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of
     * <code>sistema_vehicular.vista_inventario_completo</code>
     */
    public static final VistaInventarioCompleto VISTA_INVENTARIO_COMPLETO = new VistaInventarioCompleto();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<VistaInventarioCompletoRecord> getRecordType() {
        return VistaInventarioCompletoRecord.class;
    }

    /**
     * The column <code>sistema_vehicular.vista_inventario_completo.id</code>.
     */
    public final TableField<VistaInventarioCompletoRecord, Integer> ID = createField(DSL.name("id"), SQLDataType.INTEGER.nullable(false).defaultValue(DSL.inline("0", SQLDataType.INTEGER)), this, "");

    /**
     * The column
     * <code>sistema_vehicular.vista_inventario_completo.codigo_repuesto</code>.
     */
    public final TableField<VistaInventarioCompletoRecord, String> CODIGO_REPUESTO = createField(DSL.name("codigo_repuesto"), SQLDataType.VARCHAR(20).defaultValue(DSL.inline("NULL", SQLDataType.VARCHAR)), this, "");

    /**
     * The column
     * <code>sistema_vehicular.vista_inventario_completo.codigo_ubicacion</code>.
     */
    public final TableField<VistaInventarioCompletoRecord, String> CODIGO_UBICACION = createField(DSL.name("codigo_ubicacion"), SQLDataType.VARCHAR(100).defaultValue(DSL.inline("NULL", SQLDataType.VARCHAR)), this, "");

    /**
     * The column
     * <code>sistema_vehicular.vista_inventario_completo.parte_vehiculo</code>.
     */
    public final TableField<VistaInventarioCompletoRecord, VistaInventarioCompletoParteVehiculo> PARTE_VEHICULO = createField(DSL.name("parte_vehiculo"), SQLDataType.VARCHAR(28).nullable(false).asEnumDataType(VistaInventarioCompletoParteVehiculo.class), this, "");

    /**
     * The column
     * <code>sistema_vehicular.vista_inventario_completo.descripcion</code>.
     */
    public final TableField<VistaInventarioCompletoRecord, String> DESCRIPCION = createField(DSL.name("descripcion"), SQLDataType.CLOB.defaultValue(DSL.inline("NULL", SQLDataType.CLOB)), this, "");

    /**
     * The column
     * <code>sistema_vehicular.vista_inventario_completo.precio_costo</code>.
     */
    public final TableField<VistaInventarioCompletoRecord, BigDecimal> PRECIO_COSTO = createField(DSL.name("precio_costo"), SQLDataType.DECIMAL(10, 2).defaultValue(DSL.inline("0.00", SQLDataType.DECIMAL)), this, "");

    /**
     * The column
     * <code>sistema_vehicular.vista_inventario_completo.precio_venta</code>.
     */
    public final TableField<VistaInventarioCompletoRecord, BigDecimal> PRECIO_VENTA = createField(DSL.name("precio_venta"), SQLDataType.DECIMAL(10, 2).defaultValue(DSL.inline("0.00", SQLDataType.DECIMAL)), this, "");

    /**
     * The column
     * <code>sistema_vehicular.vista_inventario_completo.precio_mayoreo</code>.
     */
    public final TableField<VistaInventarioCompletoRecord, BigDecimal> PRECIO_MAYOREO = createField(DSL.name("precio_mayoreo"), SQLDataType.DECIMAL(10, 2).defaultValue(DSL.inline("0.00", SQLDataType.DECIMAL)), this, "");

    /**
     * The column
     * <code>sistema_vehicular.vista_inventario_completo.formula_15</code>.
     */
    public final TableField<VistaInventarioCompletoRecord, BigDecimal> FORMULA_15 = createField(DSL.name("formula_15"), SQLDataType.DECIMAL(10, 2).defaultValue(DSL.inline("NULL", SQLDataType.DECIMAL)), this, "");

    /**
     * The column
     * <code>sistema_vehicular.vista_inventario_completo.formula_30</code>.
     */
    public final TableField<VistaInventarioCompletoRecord, BigDecimal> FORMULA_30 = createField(DSL.name("formula_30"), SQLDataType.DECIMAL(10, 2).defaultValue(DSL.inline("NULL", SQLDataType.DECIMAL)), this, "");

    /**
     * The column
     * <code>sistema_vehicular.vista_inventario_completo.estado</code>.
     */
    public final TableField<VistaInventarioCompletoRecord, VistaInventarioCompletoEstado> ESTADO = createField(DSL.name("estado"), SQLDataType.VARCHAR(13).defaultValue(DSL.inline("'STOCK'", SQLDataType.VARCHAR)).asEnumDataType(VistaInventarioCompletoEstado.class), this, "");

    /**
     * The column
     * <code>sistema_vehicular.vista_inventario_completo.anio_registro</code>.
     */
    public final TableField<VistaInventarioCompletoRecord, Short> ANIO_REGISTRO = createField(DSL.name("anio_registro"), SQLDataType.SMALLINT.nullable(false), this, "");

    /**
     * The column
     * <code>sistema_vehicular.vista_inventario_completo.mes_registro</code>.
     */
    public final TableField<VistaInventarioCompletoRecord, Byte> MES_REGISTRO = createField(DSL.name("mes_registro"), SQLDataType.TINYINT.nullable(false), this, "");

    /**
     * The column
     * <code>sistema_vehicular.vista_inventario_completo.codigo_vehiculo</code>.
     */
    public final TableField<VistaInventarioCompletoRecord, String> CODIGO_VEHICULO = createField(DSL.name("codigo_vehiculo"), SQLDataType.VARCHAR(20).defaultValue(DSL.inline("NULL", SQLDataType.VARCHAR)), this, "");

    /**
     * The column
     * <code>sistema_vehicular.vista_inventario_completo.marca</code>.
     */
    public final TableField<VistaInventarioCompletoRecord, String> MARCA = createField(DSL.name("marca"), SQLDataType.VARCHAR(50), this, "");

    /**
     * The column
     * <code>sistema_vehicular.vista_inventario_completo.modelo</code>.
     */
    public final TableField<VistaInventarioCompletoRecord, String> MODELO = createField(DSL.name("modelo"), SQLDataType.VARCHAR(100), this, "");

    /**
     * The column
     * <code>sistema_vehicular.vista_inventario_completo.generacion</code>.
     */
    public final TableField<VistaInventarioCompletoRecord, String> GENERACION = createField(DSL.name("generacion"), SQLDataType.VARCHAR(50), this, "");

    /**
     * The column
     * <code>sistema_vehicular.vista_inventario_completo.anio_vehiculo</code>.
     */
    public final TableField<VistaInventarioCompletoRecord, Integer> ANIO_VEHICULO = createField(DSL.name("anio_vehiculo"), SQLDataType.INTEGER, this, "");

    /**
     * The column
     * <code>sistema_vehicular.vista_inventario_completo.clave_generacion</code>.
     */
    public final TableField<VistaInventarioCompletoRecord, String> CLAVE_GENERACION = createField(DSL.name("clave_generacion"), SQLDataType.VARCHAR(202).defaultValue(DSL.inline("NULL", SQLDataType.VARCHAR)), this, "");

    private VistaInventarioCompleto(Name alias, Table<VistaInventarioCompletoRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private VistaInventarioCompleto(Name alias, Table<VistaInventarioCompletoRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment("VIEW"), TableOptions.view("create view `vista_inventario_completo` as select `ir`.`id` AS `id`,`ir`.`codigo_repuesto` AS `codigo_repuesto`,`ir`.`codigo_ubicacion` AS `codigo_ubicacion`,`ir`.`parte_vehiculo` AS `parte_vehiculo`,`ir`.`descripcion` AS `descripcion`,`ir`.`precio_costo` AS `precio_costo`,`ir`.`precio_venta` AS `precio_venta`,`ir`.`precio_mayoreo` AS `precio_mayoreo`,`ir`.`formula_15` AS `formula_15`,`ir`.`formula_30` AS `formula_30`,`ir`.`estado` AS `estado`,`ir`.`anio_registro` AS `anio_registro`,`ir`.`mes_registro` AS `mes_registro`,`v`.`codigo_vehiculo` AS `codigo_vehiculo`,`vvc`.`marca` AS `marca`,`vvc`.`modelo` AS `modelo`,`vvc`.`generacion` AS `generacion`,`vvc`.`anio` AS `anio_vehiculo`,`vvc`.`clave_generacion` AS `clave_generacion` from ((`sistema_vehicular`.`inventario_repuestos` `ir` left join `sistema_vehicular`.`vehiculos` `v` on(`ir`.`vehiculo_origen_id` = `v`.`id`)) left join `sistema_vehicular`.`vista_vehiculos_completa` `vvc` on(`v`.`id` = `vvc`.`id`))"), where);
    }

    /**
     * Create an aliased
     * <code>sistema_vehicular.vista_inventario_completo</code> table reference
     */
    public VistaInventarioCompleto(String alias) {
        this(DSL.name(alias), VISTA_INVENTARIO_COMPLETO);
    }

    /**
     * Create an aliased
     * <code>sistema_vehicular.vista_inventario_completo</code> table reference
     */
    public VistaInventarioCompleto(Name alias) {
        this(alias, VISTA_INVENTARIO_COMPLETO);
    }

    /**
     * Create a <code>sistema_vehicular.vista_inventario_completo</code> table
     * reference
     */
    public VistaInventarioCompleto() {
        this(DSL.name("vista_inventario_completo"), null);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : SistemaVehicular.SISTEMA_VEHICULAR;
    }

    @Override
    public VistaInventarioCompleto as(String alias) {
        return new VistaInventarioCompleto(DSL.name(alias), this);
    }

    @Override
    public VistaInventarioCompleto as(Name alias) {
        return new VistaInventarioCompleto(alias, this);
    }

    @Override
    public VistaInventarioCompleto as(Table<?> alias) {
        return new VistaInventarioCompleto(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public VistaInventarioCompleto rename(String name) {
        return new VistaInventarioCompleto(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public VistaInventarioCompleto rename(Name name) {
        return new VistaInventarioCompleto(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public VistaInventarioCompleto rename(Table<?> name) {
        return new VistaInventarioCompleto(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public VistaInventarioCompleto where(Condition condition) {
        return new VistaInventarioCompleto(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public VistaInventarioCompleto where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public VistaInventarioCompleto where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public VistaInventarioCompleto where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public VistaInventarioCompleto where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public VistaInventarioCompleto where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public VistaInventarioCompleto where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public VistaInventarioCompleto where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public VistaInventarioCompleto whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public VistaInventarioCompleto whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
