/*
 * This file is generated by jOOQ.
 */
package com.RodiejaContable.database.jooq.tables;


import com.RodiejaContable.database.jooq.SistemaVehicular;
import com.RodiejaContable.database.jooq.tables.records.VistaResumenGeneracionesRecord;

import java.math.BigDecimal;
import java.util.Collection;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.Name;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * VIEW
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class VistaResumenGeneraciones extends TableImpl<VistaResumenGeneracionesRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of
     * <code>sistema_vehicular.vista_resumen_generaciones</code>
     */
    public static final VistaResumenGeneraciones VISTA_RESUMEN_GENERACIONES = new VistaResumenGeneraciones();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<VistaResumenGeneracionesRecord> getRecordType() {
        return VistaResumenGeneracionesRecord.class;
    }

    /**
     * The column
     * <code>sistema_vehicular.vista_resumen_generaciones.generacion_id</code>.
     */
    public final TableField<VistaResumenGeneracionesRecord, Integer> GENERACION_ID = createField(DSL.name("generacion_id"), SQLDataType.INTEGER.nullable(false).defaultValue(DSL.inline("0", SQLDataType.INTEGER)), this, "");

    /**
     * The column
     * <code>sistema_vehicular.vista_resumen_generaciones.marca</code>.
     */
    public final TableField<VistaResumenGeneracionesRecord, String> MARCA = createField(DSL.name("marca"), SQLDataType.VARCHAR(50).nullable(false), this, "");

    /**
     * The column
     * <code>sistema_vehicular.vista_resumen_generaciones.modelo</code>.
     */
    public final TableField<VistaResumenGeneracionesRecord, String> MODELO = createField(DSL.name("modelo"), SQLDataType.VARCHAR(100).nullable(false), this, "");

    /**
     * The column
     * <code>sistema_vehicular.vista_resumen_generaciones.generacion</code>.
     */
    public final TableField<VistaResumenGeneracionesRecord, String> GENERACION = createField(DSL.name("generacion"), SQLDataType.VARCHAR(50).nullable(false), this, "");

    /**
     * The column
     * <code>sistema_vehicular.vista_resumen_generaciones.descripcion</code>.
     */
    public final TableField<VistaResumenGeneracionesRecord, String> DESCRIPCION = createField(DSL.name("descripcion"), SQLDataType.VARCHAR(200).defaultValue(DSL.inline("NULL", SQLDataType.VARCHAR)), this, "");

    /**
     * The column
     * <code>sistema_vehicular.vista_resumen_generaciones.clave_generacion</code>.
     */
    public final TableField<VistaResumenGeneracionesRecord, String> CLAVE_GENERACION = createField(DSL.name("clave_generacion"), SQLDataType.VARCHAR(202).defaultValue(DSL.inline("NULL", SQLDataType.VARCHAR)), this, "");

    /**
     * The column
     * <code>sistema_vehicular.vista_resumen_generaciones.anio_inicio</code>.
     */
    public final TableField<VistaResumenGeneracionesRecord, Integer> ANIO_INICIO = createField(DSL.name("anio_inicio"), SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column
     * <code>sistema_vehicular.vista_resumen_generaciones.anio_fin</code>.
     */
    public final TableField<VistaResumenGeneracionesRecord, Integer> ANIO_FIN = createField(DSL.name("anio_fin"), SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column
     * <code>sistema_vehicular.vista_resumen_generaciones.total_vehiculos</code>.
     */
    public final TableField<VistaResumenGeneracionesRecord, Long> TOTAL_VEHICULOS = createField(DSL.name("total_vehiculos"), SQLDataType.BIGINT.nullable(false).defaultValue(DSL.inline("0", SQLDataType.BIGINT)), this, "");

    /**
     * The column
     * <code>sistema_vehicular.vista_resumen_generaciones.total_repuestos</code>.
     */
    public final TableField<VistaResumenGeneracionesRecord, Long> TOTAL_REPUESTOS = createField(DSL.name("total_repuestos"), SQLDataType.BIGINT.nullable(false).defaultValue(DSL.inline("0", SQLDataType.BIGINT)), this, "");

    /**
     * The column
     * <code>sistema_vehicular.vista_resumen_generaciones.total_inversion</code>.
     */
    public final TableField<VistaResumenGeneracionesRecord, BigDecimal> TOTAL_INVERSION = createField(DSL.name("total_inversion"), SQLDataType.DECIMAL(15, 2).defaultValue(DSL.inline("0.00", SQLDataType.DECIMAL)), this, "");

    /**
     * The column
     * <code>sistema_vehicular.vista_resumen_generaciones.total_ingresos</code>.
     */
    public final TableField<VistaResumenGeneracionesRecord, BigDecimal> TOTAL_INGRESOS = createField(DSL.name("total_ingresos"), SQLDataType.DECIMAL(15, 2).defaultValue(DSL.inline("0.00", SQLDataType.DECIMAL)), this, "");

    /**
     * The column
     * <code>sistema_vehicular.vista_resumen_generaciones.total_egresos</code>.
     */
    public final TableField<VistaResumenGeneracionesRecord, BigDecimal> TOTAL_EGRESOS = createField(DSL.name("total_egresos"), SQLDataType.DECIMAL(15, 2).defaultValue(DSL.inline("0.00", SQLDataType.DECIMAL)), this, "");

    /**
     * The column
     * <code>sistema_vehicular.vista_resumen_generaciones.balance_neto</code>.
     */
    public final TableField<VistaResumenGeneracionesRecord, BigDecimal> BALANCE_NETO = createField(DSL.name("balance_neto"), SQLDataType.DECIMAL(15, 2).defaultValue(DSL.inline("0.00", SQLDataType.DECIMAL)), this, "");

    /**
     * The column
     * <code>sistema_vehicular.vista_resumen_generaciones.porcentaje_retorno</code>.
     */
    public final TableField<VistaResumenGeneracionesRecord, BigDecimal> PORCENTAJE_RETORNO = createField(DSL.name("porcentaje_retorno"), SQLDataType.DECIMAL(21, 2).defaultValue(DSL.inline("NULL", SQLDataType.DECIMAL)), this, "");

    private VistaResumenGeneraciones(Name alias, Table<VistaResumenGeneracionesRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private VistaResumenGeneraciones(Name alias, Table<VistaResumenGeneracionesRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment("VIEW"), TableOptions.view("create view `vista_resumen_generaciones` as select `g`.`id` AS `generacion_id`,`m`.`nombre` AS `marca`,`mo`.`nombre` AS `modelo`,`g`.`nombre` AS `generacion`,`g`.`descripcion` AS `descripcion`,concat(`m`.`nombre`,'-',`mo`.`nombre`,'-',`g`.`nombre`) AS `clave_generacion`,`g`.`anio_inicio` AS `anio_inicio`,`g`.`anio_fin` AS `anio_fin`,count(distinct `v`.`id`) AS `total_vehiculos`,count(distinct `ir`.`id`) AS `total_repuestos`,`g`.`total_inversion` AS `total_inversion`,`g`.`total_ingresos` AS `total_ingresos`,`g`.`total_egresos` AS `total_egresos`,`g`.`balance_neto` AS `balance_neto`,case when `g`.`total_inversion` > 0 then round(`g`.`balance_neto` / `g`.`total_inversion` * 100,2) else 0 end AS `porcentaje_retorno` from ((((`sistema_vehicular`.`generaciones` `g` join `sistema_vehicular`.`modelos` `mo` on(`g`.`modelo_id` = `mo`.`id`)) join `sistema_vehicular`.`marcas` `m` on(`mo`.`marca_id` = `m`.`id`)) left join `sistema_vehicular`.`vehiculos` `v` on(`g`.`id` = `v`.`generacion_id` and `v`.`activo` = 1)) left join `sistema_vehicular`.`inventario_repuestos` `ir` on(`v`.`id` = `ir`.`vehiculo_origen_id` and `ir`.`estado` = 'STOCK')) where `g`.`activo` = 1 group by `g`.`id`,`m`.`nombre`,`mo`.`nombre`,`g`.`nombre`,`g`.`descripcion`,`g`.`anio_inicio`,`g`.`anio_fin`,`g`.`total_inversion`,`g`.`total_ingresos`,`g`.`total_egresos`,`g`.`balance_neto`"), where);
    }

    /**
     * Create an aliased
     * <code>sistema_vehicular.vista_resumen_generaciones</code> table reference
     */
    public VistaResumenGeneraciones(String alias) {
        this(DSL.name(alias), VISTA_RESUMEN_GENERACIONES);
    }

    /**
     * Create an aliased
     * <code>sistema_vehicular.vista_resumen_generaciones</code> table reference
     */
    public VistaResumenGeneraciones(Name alias) {
        this(alias, VISTA_RESUMEN_GENERACIONES);
    }

    /**
     * Create a <code>sistema_vehicular.vista_resumen_generaciones</code> table
     * reference
     */
    public VistaResumenGeneraciones() {
        this(DSL.name("vista_resumen_generaciones"), null);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : SistemaVehicular.SISTEMA_VEHICULAR;
    }

    @Override
    public VistaResumenGeneraciones as(String alias) {
        return new VistaResumenGeneraciones(DSL.name(alias), this);
    }

    @Override
    public VistaResumenGeneraciones as(Name alias) {
        return new VistaResumenGeneraciones(alias, this);
    }

    @Override
    public VistaResumenGeneraciones as(Table<?> alias) {
        return new VistaResumenGeneraciones(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public VistaResumenGeneraciones rename(String name) {
        return new VistaResumenGeneraciones(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public VistaResumenGeneraciones rename(Name name) {
        return new VistaResumenGeneraciones(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public VistaResumenGeneraciones rename(Table<?> name) {
        return new VistaResumenGeneraciones(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public VistaResumenGeneraciones where(Condition condition) {
        return new VistaResumenGeneraciones(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public VistaResumenGeneraciones where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public VistaResumenGeneraciones where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public VistaResumenGeneraciones where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public VistaResumenGeneraciones where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public VistaResumenGeneraciones where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public VistaResumenGeneraciones where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public VistaResumenGeneraciones where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public VistaResumenGeneraciones whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public VistaResumenGeneraciones whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
