/*
 * This file is generated by jOOQ.
 */
package com.rodiejacontable.database.jooq.enums;


import org.jooq.Catalog;
import org.jooq.EnumType;
import org.jooq.Schema;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public enum InventarioRepuestosUbicadoEnVehiculo_1 implements EnumType {

    _0_("0-"),

    REPUESTO_EN_VEHICULO("REPUESTO EN VEHICULO");

    private final String literal;

    private InventarioRepuestosUbicadoEnVehiculo_1(String literal) {
        this.literal = literal;
    }

    @Override
    public Catalog getCatalog() {
        return null;
    }

    @Override
    public Schema getSchema() {
        return null;
    }

    @Override
    public String getName() {
        return null;
    }

    @Override
    public String getLiteral() {
        return literal;
    }

    /**
     * Lookup a value of this EnumType by its literal
     */
    public static InventarioRepuestosUbicadoEnVehiculo_1 lookupLiteral(String literal) {
        return EnumType.lookupLiteral(InventarioRepuestosUbicadoEnVehiculo_1.class, literal);
    }
}
