/*
 * This file is generated by jOOQ.
 */
package com.rodiejacontable.database.jooq.tables.records;


import com.rodiejacontable.database.jooq.enums.VehiculosEstado;
import com.rodiejacontable.database.jooq.tables.Vehiculos;

import java.math.BigDecimal;
import java.time.LocalDate;
import java.time.LocalDateTime;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record16;
import org.jooq.Row16;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class VehiculosRecord extends UpdatableRecordImpl<VehiculosRecord> implements Record16<Integer, String, Integer, Integer, BigDecimal, BigDecimal, BigDecimal, BigDecimal, LocalDate, VehiculosEstado, BigDecimal, LocalDate, Byte, String, LocalDateTime, LocalDateTime> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>sistema_vehicular.vehiculos.id</code>.
     */
    public VehiculosRecord setId(Integer value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>sistema_vehicular.vehiculos.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>sistema_vehicular.vehiculos.codigo_vehiculo</code>.
     */
    public VehiculosRecord setCodigoVehiculo(String value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>sistema_vehicular.vehiculos.codigo_vehiculo</code>.
     */
    public String getCodigoVehiculo() {
        return (String) get(1);
    }

    /**
     * Setter for <code>sistema_vehicular.vehiculos.generacion_id</code>.
     */
    public VehiculosRecord setGeneracionId(Integer value) {
        set(2, value);
        return this;
    }

    /**
     * Getter for <code>sistema_vehicular.vehiculos.generacion_id</code>.
     */
    public Integer getGeneracionId() {
        return (Integer) get(2);
    }

    /**
     * Setter for <code>sistema_vehicular.vehiculos.anio</code>.
     */
    public VehiculosRecord setAnio(Integer value) {
        set(3, value);
        return this;
    }

    /**
     * Getter for <code>sistema_vehicular.vehiculos.anio</code>.
     */
    public Integer getAnio() {
        return (Integer) get(3);
    }

    /**
     * Setter for <code>sistema_vehicular.vehiculos.precio_compra</code>.
     */
    public VehiculosRecord setPrecioCompra(BigDecimal value) {
        set(4, value);
        return this;
    }

    /**
     * Getter for <code>sistema_vehicular.vehiculos.precio_compra</code>.
     */
    public BigDecimal getPrecioCompra() {
        return (BigDecimal) get(4);
    }

    /**
     * Setter for <code>sistema_vehicular.vehiculos.costo_grua</code>.
     */
    public VehiculosRecord setCostoGrua(BigDecimal value) {
        set(5, value);
        return this;
    }

    /**
     * Getter for <code>sistema_vehicular.vehiculos.costo_grua</code>.
     */
    public BigDecimal getCostoGrua() {
        return (BigDecimal) get(5);
    }

    /**
     * Setter for <code>sistema_vehicular.vehiculos.comisiones</code>.
     */
    public VehiculosRecord setComisiones(BigDecimal value) {
        set(6, value);
        return this;
    }

    /**
     * Getter for <code>sistema_vehicular.vehiculos.comisiones</code>.
     */
    public BigDecimal getComisiones() {
        return (BigDecimal) get(6);
    }

    /**
     * Setter for <code>sistema_vehicular.vehiculos.inversion_total</code>.
     */
    public VehiculosRecord setInversionTotal(BigDecimal value) {
        set(7, value);
        return this;
    }

    /**
     * Getter for <code>sistema_vehicular.vehiculos.inversion_total</code>.
     */
    public BigDecimal getInversionTotal() {
        return (BigDecimal) get(7);
    }

    /**
     * Setter for <code>sistema_vehicular.vehiculos.fecha_ingreso</code>.
     */
    public VehiculosRecord setFechaIngreso(LocalDate value) {
        set(8, value);
        return this;
    }

    /**
     * Getter for <code>sistema_vehicular.vehiculos.fecha_ingreso</code>.
     */
    public LocalDate getFechaIngreso() {
        return (LocalDate) get(8);
    }

    /**
     * Setter for <code>sistema_vehicular.vehiculos.estado</code>.
     */
    public VehiculosRecord setEstado(VehiculosEstado value) {
        set(9, value);
        return this;
    }

    /**
     * Getter for <code>sistema_vehicular.vehiculos.estado</code>.
     */
    public VehiculosEstado getEstado() {
        return (VehiculosEstado) get(9);
    }

    /**
     * Setter for <code>sistema_vehicular.vehiculos.precio_venta</code>.
     */
    public VehiculosRecord setPrecioVenta(BigDecimal value) {
        set(10, value);
        return this;
    }

    /**
     * Getter for <code>sistema_vehicular.vehiculos.precio_venta</code>.
     */
    public BigDecimal getPrecioVenta() {
        return (BigDecimal) get(10);
    }

    /**
     * Setter for <code>sistema_vehicular.vehiculos.fecha_venta</code>.
     */
    public VehiculosRecord setFechaVenta(LocalDate value) {
        set(11, value);
        return this;
    }

    /**
     * Getter for <code>sistema_vehicular.vehiculos.fecha_venta</code>.
     */
    public LocalDate getFechaVenta() {
        return (LocalDate) get(11);
    }

    /**
     * Setter for <code>sistema_vehicular.vehiculos.activo</code>.
     */
    public VehiculosRecord setActivo(Byte value) {
        set(12, value);
        return this;
    }

    /**
     * Getter for <code>sistema_vehicular.vehiculos.activo</code>.
     */
    public Byte getActivo() {
        return (Byte) get(12);
    }

    /**
     * Setter for <code>sistema_vehicular.vehiculos.notas</code>.
     */
    public VehiculosRecord setNotas(String value) {
        set(13, value);
        return this;
    }

    /**
     * Getter for <code>sistema_vehicular.vehiculos.notas</code>.
     */
    public String getNotas() {
        return (String) get(13);
    }

    /**
     * Setter for <code>sistema_vehicular.vehiculos.fecha_creacion</code>.
     */
    public VehiculosRecord setFechaCreacion(LocalDateTime value) {
        set(14, value);
        return this;
    }

    /**
     * Getter for <code>sistema_vehicular.vehiculos.fecha_creacion</code>.
     */
    public LocalDateTime getFechaCreacion() {
        return (LocalDateTime) get(14);
    }

    /**
     * Setter for <code>sistema_vehicular.vehiculos.fecha_actualizacion</code>.
     */
    public VehiculosRecord setFechaActualizacion(LocalDateTime value) {
        set(15, value);
        return this;
    }

    /**
     * Getter for <code>sistema_vehicular.vehiculos.fecha_actualizacion</code>.
     */
    public LocalDateTime getFechaActualizacion() {
        return (LocalDateTime) get(15);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record16 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row16<Integer, String, Integer, Integer, BigDecimal, BigDecimal, BigDecimal, BigDecimal, LocalDate, VehiculosEstado, BigDecimal, LocalDate, Byte, String, LocalDateTime, LocalDateTime> fieldsRow() {
        return (Row16) super.fieldsRow();
    }

    @Override
    public Row16<Integer, String, Integer, Integer, BigDecimal, BigDecimal, BigDecimal, BigDecimal, LocalDate, VehiculosEstado, BigDecimal, LocalDate, Byte, String, LocalDateTime, LocalDateTime> valuesRow() {
        return (Row16) super.valuesRow();
    }

    @Override
    public Field<Integer> field1() {
        return Vehiculos.VEHICULOS.ID;
    }

    @Override
    public Field<String> field2() {
        return Vehiculos.VEHICULOS.CODIGO_VEHICULO;
    }

    @Override
    public Field<Integer> field3() {
        return Vehiculos.VEHICULOS.GENERACION_ID;
    }

    @Override
    public Field<Integer> field4() {
        return Vehiculos.VEHICULOS.ANIO;
    }

    @Override
    public Field<BigDecimal> field5() {
        return Vehiculos.VEHICULOS.PRECIO_COMPRA;
    }

    @Override
    public Field<BigDecimal> field6() {
        return Vehiculos.VEHICULOS.COSTO_GRUA;
    }

    @Override
    public Field<BigDecimal> field7() {
        return Vehiculos.VEHICULOS.COMISIONES;
    }

    @Override
    public Field<BigDecimal> field8() {
        return Vehiculos.VEHICULOS.INVERSION_TOTAL;
    }

    @Override
    public Field<LocalDate> field9() {
        return Vehiculos.VEHICULOS.FECHA_INGRESO;
    }

    @Override
    public Field<VehiculosEstado> field10() {
        return Vehiculos.VEHICULOS.ESTADO;
    }

    @Override
    public Field<BigDecimal> field11() {
        return Vehiculos.VEHICULOS.PRECIO_VENTA;
    }

    @Override
    public Field<LocalDate> field12() {
        return Vehiculos.VEHICULOS.FECHA_VENTA;
    }

    @Override
    public Field<Byte> field13() {
        return Vehiculos.VEHICULOS.ACTIVO;
    }

    @Override
    public Field<String> field14() {
        return Vehiculos.VEHICULOS.NOTAS;
    }

    @Override
    public Field<LocalDateTime> field15() {
        return Vehiculos.VEHICULOS.FECHA_CREACION;
    }

    @Override
    public Field<LocalDateTime> field16() {
        return Vehiculos.VEHICULOS.FECHA_ACTUALIZACION;
    }

    @Override
    public Integer component1() {
        return getId();
    }

    @Override
    public String component2() {
        return getCodigoVehiculo();
    }

    @Override
    public Integer component3() {
        return getGeneracionId();
    }

    @Override
    public Integer component4() {
        return getAnio();
    }

    @Override
    public BigDecimal component5() {
        return getPrecioCompra();
    }

    @Override
    public BigDecimal component6() {
        return getCostoGrua();
    }

    @Override
    public BigDecimal component7() {
        return getComisiones();
    }

    @Override
    public BigDecimal component8() {
        return getInversionTotal();
    }

    @Override
    public LocalDate component9() {
        return getFechaIngreso();
    }

    @Override
    public VehiculosEstado component10() {
        return getEstado();
    }

    @Override
    public BigDecimal component11() {
        return getPrecioVenta();
    }

    @Override
    public LocalDate component12() {
        return getFechaVenta();
    }

    @Override
    public Byte component13() {
        return getActivo();
    }

    @Override
    public String component14() {
        return getNotas();
    }

    @Override
    public LocalDateTime component15() {
        return getFechaCreacion();
    }

    @Override
    public LocalDateTime component16() {
        return getFechaActualizacion();
    }

    @Override
    public Integer value1() {
        return getId();
    }

    @Override
    public String value2() {
        return getCodigoVehiculo();
    }

    @Override
    public Integer value3() {
        return getGeneracionId();
    }

    @Override
    public Integer value4() {
        return getAnio();
    }

    @Override
    public BigDecimal value5() {
        return getPrecioCompra();
    }

    @Override
    public BigDecimal value6() {
        return getCostoGrua();
    }

    @Override
    public BigDecimal value7() {
        return getComisiones();
    }

    @Override
    public BigDecimal value8() {
        return getInversionTotal();
    }

    @Override
    public LocalDate value9() {
        return getFechaIngreso();
    }

    @Override
    public VehiculosEstado value10() {
        return getEstado();
    }

    @Override
    public BigDecimal value11() {
        return getPrecioVenta();
    }

    @Override
    public LocalDate value12() {
        return getFechaVenta();
    }

    @Override
    public Byte value13() {
        return getActivo();
    }

    @Override
    public String value14() {
        return getNotas();
    }

    @Override
    public LocalDateTime value15() {
        return getFechaCreacion();
    }

    @Override
    public LocalDateTime value16() {
        return getFechaActualizacion();
    }

    @Override
    public VehiculosRecord value1(Integer value) {
        setId(value);
        return this;
    }

    @Override
    public VehiculosRecord value2(String value) {
        setCodigoVehiculo(value);
        return this;
    }

    @Override
    public VehiculosRecord value3(Integer value) {
        setGeneracionId(value);
        return this;
    }

    @Override
    public VehiculosRecord value4(Integer value) {
        setAnio(value);
        return this;
    }

    @Override
    public VehiculosRecord value5(BigDecimal value) {
        setPrecioCompra(value);
        return this;
    }

    @Override
    public VehiculosRecord value6(BigDecimal value) {
        setCostoGrua(value);
        return this;
    }

    @Override
    public VehiculosRecord value7(BigDecimal value) {
        setComisiones(value);
        return this;
    }

    @Override
    public VehiculosRecord value8(BigDecimal value) {
        setInversionTotal(value);
        return this;
    }

    @Override
    public VehiculosRecord value9(LocalDate value) {
        setFechaIngreso(value);
        return this;
    }

    @Override
    public VehiculosRecord value10(VehiculosEstado value) {
        setEstado(value);
        return this;
    }

    @Override
    public VehiculosRecord value11(BigDecimal value) {
        setPrecioVenta(value);
        return this;
    }

    @Override
    public VehiculosRecord value12(LocalDate value) {
        setFechaVenta(value);
        return this;
    }

    @Override
    public VehiculosRecord value13(Byte value) {
        setActivo(value);
        return this;
    }

    @Override
    public VehiculosRecord value14(String value) {
        setNotas(value);
        return this;
    }

    @Override
    public VehiculosRecord value15(LocalDateTime value) {
        setFechaCreacion(value);
        return this;
    }

    @Override
    public VehiculosRecord value16(LocalDateTime value) {
        setFechaActualizacion(value);
        return this;
    }

    @Override
    public VehiculosRecord values(Integer value1, String value2, Integer value3, Integer value4, BigDecimal value5, BigDecimal value6, BigDecimal value7, BigDecimal value8, LocalDate value9, VehiculosEstado value10, BigDecimal value11, LocalDate value12, Byte value13, String value14, LocalDateTime value15, LocalDateTime value16) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        value10(value10);
        value11(value11);
        value12(value12);
        value13(value13);
        value14(value14);
        value15(value15);
        value16(value16);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached VehiculosRecord
     */
    public VehiculosRecord() {
        super(Vehiculos.VEHICULOS);
    }

    /**
     * Create a detached, initialised VehiculosRecord
     */
    public VehiculosRecord(Integer id, String codigoVehiculo, Integer generacionId, Integer anio, BigDecimal precioCompra, BigDecimal costoGrua, BigDecimal comisiones, BigDecimal inversionTotal, LocalDate fechaIngreso, VehiculosEstado estado, BigDecimal precioVenta, LocalDate fechaVenta, Byte activo, String notas, LocalDateTime fechaCreacion, LocalDateTime fechaActualizacion) {
        super(Vehiculos.VEHICULOS);

        setId(id);
        setCodigoVehiculo(codigoVehiculo);
        setGeneracionId(generacionId);
        setAnio(anio);
        setPrecioCompra(precioCompra);
        setCostoGrua(costoGrua);
        setComisiones(comisiones);
        setInversionTotal(inversionTotal);
        setFechaIngreso(fechaIngreso);
        setEstado(estado);
        setPrecioVenta(precioVenta);
        setFechaVenta(fechaVenta);
        setActivo(activo);
        setNotas(notas);
        setFechaCreacion(fechaCreacion);
        setFechaActualizacion(fechaActualizacion);
        resetChangedOnNotNull();
    }

    /**
     * Create a detached, initialised VehiculosRecord
     */
    public VehiculosRecord(com.rodiejacontable.database.jooq.tables.pojos.Vehiculos value) {
        super(Vehiculos.VEHICULOS);

        if (value != null) {
            setId(value.getId());
            setCodigoVehiculo(value.getCodigoVehiculo());
            setGeneracionId(value.getGeneracionId());
            setAnio(value.getAnio());
            setPrecioCompra(value.getPrecioCompra());
            setCostoGrua(value.getCostoGrua());
            setComisiones(value.getComisiones());
            setInversionTotal(value.getInversionTotal());
            setFechaIngreso(value.getFechaIngreso());
            setEstado(value.getEstado());
            setPrecioVenta(value.getPrecioVenta());
            setFechaVenta(value.getFechaVenta());
            setActivo(value.getActivo());
            setNotas(value.getNotas());
            setFechaCreacion(value.getFechaCreacion());
            setFechaActualizacion(value.getFechaActualizacion());
            resetChangedOnNotNull();
        }
    }
}
