/*
 * This file is generated by jOOQ.
 */
package com.rodiejacontable.database.jooq.tables.records;


import com.rodiejacontable.database.jooq.tables.VistaAnalisisFinancieroMensual;

import java.math.BigDecimal;

import org.jooq.Field;
import org.jooq.Record12;
import org.jooq.Row12;
import org.jooq.impl.TableRecordImpl;


/**
 * VIEW
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class VistaAnalisisFinancieroMensualRecord extends TableRecordImpl<VistaAnalisisFinancieroMensualRecord> implements Record12<Integer, Integer, String, Long, BigDecimal, BigDecimal, BigDecimal, BigDecimal, Long, Long, BigDecimal, BigDecimal> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for
     * <code>sistema_vehicular.vista_analisis_financiero_mensual.anio</code>.
     */
    public VistaAnalisisFinancieroMensualRecord setAnio(Integer value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for
     * <code>sistema_vehicular.vista_analisis_financiero_mensual.anio</code>.
     */
    public Integer getAnio() {
        return (Integer) get(0);
    }

    /**
     * Setter for
     * <code>sistema_vehicular.vista_analisis_financiero_mensual.mes</code>.
     */
    public VistaAnalisisFinancieroMensualRecord setMes(Integer value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for
     * <code>sistema_vehicular.vista_analisis_financiero_mensual.mes</code>.
     */
    public Integer getMes() {
        return (Integer) get(1);
    }

    /**
     * Setter for
     * <code>sistema_vehicular.vista_analisis_financiero_mensual.nombre_mes</code>.
     */
    public VistaAnalisisFinancieroMensualRecord setNombreMes(String value) {
        set(2, value);
        return this;
    }

    /**
     * Getter for
     * <code>sistema_vehicular.vista_analisis_financiero_mensual.nombre_mes</code>.
     */
    public String getNombreMes() {
        return (String) get(2);
    }

    /**
     * Setter for
     * <code>sistema_vehicular.vista_analisis_financiero_mensual.total_transacciones</code>.
     */
    public VistaAnalisisFinancieroMensualRecord setTotalTransacciones(Long value) {
        set(3, value);
        return this;
    }

    /**
     * Getter for
     * <code>sistema_vehicular.vista_analisis_financiero_mensual.total_transacciones</code>.
     */
    public Long getTotalTransacciones() {
        return (Long) get(3);
    }

    /**
     * Setter for
     * <code>sistema_vehicular.vista_analisis_financiero_mensual.total_ingresos</code>.
     */
    public VistaAnalisisFinancieroMensualRecord setTotalIngresos(BigDecimal value) {
        set(4, value);
        return this;
    }

    /**
     * Getter for
     * <code>sistema_vehicular.vista_analisis_financiero_mensual.total_ingresos</code>.
     */
    public BigDecimal getTotalIngresos() {
        return (BigDecimal) get(4);
    }

    /**
     * Setter for
     * <code>sistema_vehicular.vista_analisis_financiero_mensual.total_egresos</code>.
     */
    public VistaAnalisisFinancieroMensualRecord setTotalEgresos(BigDecimal value) {
        set(5, value);
        return this;
    }

    /**
     * Getter for
     * <code>sistema_vehicular.vista_analisis_financiero_mensual.total_egresos</code>.
     */
    public BigDecimal getTotalEgresos() {
        return (BigDecimal) get(5);
    }

    /**
     * Setter for
     * <code>sistema_vehicular.vista_analisis_financiero_mensual.balance_neto</code>.
     */
    public VistaAnalisisFinancieroMensualRecord setBalanceNeto(BigDecimal value) {
        set(6, value);
        return this;
    }

    /**
     * Getter for
     * <code>sistema_vehicular.vista_analisis_financiero_mensual.balance_neto</code>.
     */
    public BigDecimal getBalanceNeto() {
        return (BigDecimal) get(6);
    }

    /**
     * Setter for
     * <code>sistema_vehicular.vista_analisis_financiero_mensual.total_comisiones</code>.
     */
    public VistaAnalisisFinancieroMensualRecord setTotalComisiones(BigDecimal value) {
        set(7, value);
        return this;
    }

    /**
     * Getter for
     * <code>sistema_vehicular.vista_analisis_financiero_mensual.total_comisiones</code>.
     */
    public BigDecimal getTotalComisiones() {
        return (BigDecimal) get(7);
    }

    /**
     * Setter for
     * <code>sistema_vehicular.vista_analisis_financiero_mensual.vehiculos_vendidos</code>.
     */
    public VistaAnalisisFinancieroMensualRecord setVehiculosVendidos(Long value) {
        set(8, value);
        return this;
    }

    /**
     * Getter for
     * <code>sistema_vehicular.vista_analisis_financiero_mensual.vehiculos_vendidos</code>.
     */
    public Long getVehiculosVendidos() {
        return (Long) get(8);
    }

    /**
     * Setter for
     * <code>sistema_vehicular.vista_analisis_financiero_mensual.repuestos_vendidos</code>.
     */
    public VistaAnalisisFinancieroMensualRecord setRepuestosVendidos(Long value) {
        set(9, value);
        return this;
    }

    /**
     * Getter for
     * <code>sistema_vehicular.vista_analisis_financiero_mensual.repuestos_vendidos</code>.
     */
    public Long getRepuestosVendidos() {
        return (Long) get(9);
    }

    /**
     * Setter for
     * <code>sistema_vehicular.vista_analisis_financiero_mensual.promedio_venta</code>.
     */
    public VistaAnalisisFinancieroMensualRecord setPromedioVenta(BigDecimal value) {
        set(10, value);
        return this;
    }

    /**
     * Getter for
     * <code>sistema_vehicular.vista_analisis_financiero_mensual.promedio_venta</code>.
     */
    public BigDecimal getPromedioVenta() {
        return (BigDecimal) get(10);
    }

    /**
     * Setter for
     * <code>sistema_vehicular.vista_analisis_financiero_mensual.ratio_ingresos_egresos</code>.
     */
    public VistaAnalisisFinancieroMensualRecord setRatioIngresosEgresos(BigDecimal value) {
        set(11, value);
        return this;
    }

    /**
     * Getter for
     * <code>sistema_vehicular.vista_analisis_financiero_mensual.ratio_ingresos_egresos</code>.
     */
    public BigDecimal getRatioIngresosEgresos() {
        return (BigDecimal) get(11);
    }

    // -------------------------------------------------------------------------
    // Record12 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row12<Integer, Integer, String, Long, BigDecimal, BigDecimal, BigDecimal, BigDecimal, Long, Long, BigDecimal, BigDecimal> fieldsRow() {
        return (Row12) super.fieldsRow();
    }

    @Override
    public Row12<Integer, Integer, String, Long, BigDecimal, BigDecimal, BigDecimal, BigDecimal, Long, Long, BigDecimal, BigDecimal> valuesRow() {
        return (Row12) super.valuesRow();
    }

    @Override
    public Field<Integer> field1() {
        return VistaAnalisisFinancieroMensual.VISTA_ANALISIS_FINANCIERO_MENSUAL.ANIO;
    }

    @Override
    public Field<Integer> field2() {
        return VistaAnalisisFinancieroMensual.VISTA_ANALISIS_FINANCIERO_MENSUAL.MES;
    }

    @Override
    public Field<String> field3() {
        return VistaAnalisisFinancieroMensual.VISTA_ANALISIS_FINANCIERO_MENSUAL.NOMBRE_MES;
    }

    @Override
    public Field<Long> field4() {
        return VistaAnalisisFinancieroMensual.VISTA_ANALISIS_FINANCIERO_MENSUAL.TOTAL_TRANSACCIONES;
    }

    @Override
    public Field<BigDecimal> field5() {
        return VistaAnalisisFinancieroMensual.VISTA_ANALISIS_FINANCIERO_MENSUAL.TOTAL_INGRESOS;
    }

    @Override
    public Field<BigDecimal> field6() {
        return VistaAnalisisFinancieroMensual.VISTA_ANALISIS_FINANCIERO_MENSUAL.TOTAL_EGRESOS;
    }

    @Override
    public Field<BigDecimal> field7() {
        return VistaAnalisisFinancieroMensual.VISTA_ANALISIS_FINANCIERO_MENSUAL.BALANCE_NETO;
    }

    @Override
    public Field<BigDecimal> field8() {
        return VistaAnalisisFinancieroMensual.VISTA_ANALISIS_FINANCIERO_MENSUAL.TOTAL_COMISIONES;
    }

    @Override
    public Field<Long> field9() {
        return VistaAnalisisFinancieroMensual.VISTA_ANALISIS_FINANCIERO_MENSUAL.VEHICULOS_VENDIDOS;
    }

    @Override
    public Field<Long> field10() {
        return VistaAnalisisFinancieroMensual.VISTA_ANALISIS_FINANCIERO_MENSUAL.REPUESTOS_VENDIDOS;
    }

    @Override
    public Field<BigDecimal> field11() {
        return VistaAnalisisFinancieroMensual.VISTA_ANALISIS_FINANCIERO_MENSUAL.PROMEDIO_VENTA;
    }

    @Override
    public Field<BigDecimal> field12() {
        return VistaAnalisisFinancieroMensual.VISTA_ANALISIS_FINANCIERO_MENSUAL.RATIO_INGRESOS_EGRESOS;
    }

    @Override
    public Integer component1() {
        return getAnio();
    }

    @Override
    public Integer component2() {
        return getMes();
    }

    @Override
    public String component3() {
        return getNombreMes();
    }

    @Override
    public Long component4() {
        return getTotalTransacciones();
    }

    @Override
    public BigDecimal component5() {
        return getTotalIngresos();
    }

    @Override
    public BigDecimal component6() {
        return getTotalEgresos();
    }

    @Override
    public BigDecimal component7() {
        return getBalanceNeto();
    }

    @Override
    public BigDecimal component8() {
        return getTotalComisiones();
    }

    @Override
    public Long component9() {
        return getVehiculosVendidos();
    }

    @Override
    public Long component10() {
        return getRepuestosVendidos();
    }

    @Override
    public BigDecimal component11() {
        return getPromedioVenta();
    }

    @Override
    public BigDecimal component12() {
        return getRatioIngresosEgresos();
    }

    @Override
    public Integer value1() {
        return getAnio();
    }

    @Override
    public Integer value2() {
        return getMes();
    }

    @Override
    public String value3() {
        return getNombreMes();
    }

    @Override
    public Long value4() {
        return getTotalTransacciones();
    }

    @Override
    public BigDecimal value5() {
        return getTotalIngresos();
    }

    @Override
    public BigDecimal value6() {
        return getTotalEgresos();
    }

    @Override
    public BigDecimal value7() {
        return getBalanceNeto();
    }

    @Override
    public BigDecimal value8() {
        return getTotalComisiones();
    }

    @Override
    public Long value9() {
        return getVehiculosVendidos();
    }

    @Override
    public Long value10() {
        return getRepuestosVendidos();
    }

    @Override
    public BigDecimal value11() {
        return getPromedioVenta();
    }

    @Override
    public BigDecimal value12() {
        return getRatioIngresosEgresos();
    }

    @Override
    public VistaAnalisisFinancieroMensualRecord value1(Integer value) {
        setAnio(value);
        return this;
    }

    @Override
    public VistaAnalisisFinancieroMensualRecord value2(Integer value) {
        setMes(value);
        return this;
    }

    @Override
    public VistaAnalisisFinancieroMensualRecord value3(String value) {
        setNombreMes(value);
        return this;
    }

    @Override
    public VistaAnalisisFinancieroMensualRecord value4(Long value) {
        setTotalTransacciones(value);
        return this;
    }

    @Override
    public VistaAnalisisFinancieroMensualRecord value5(BigDecimal value) {
        setTotalIngresos(value);
        return this;
    }

    @Override
    public VistaAnalisisFinancieroMensualRecord value6(BigDecimal value) {
        setTotalEgresos(value);
        return this;
    }

    @Override
    public VistaAnalisisFinancieroMensualRecord value7(BigDecimal value) {
        setBalanceNeto(value);
        return this;
    }

    @Override
    public VistaAnalisisFinancieroMensualRecord value8(BigDecimal value) {
        setTotalComisiones(value);
        return this;
    }

    @Override
    public VistaAnalisisFinancieroMensualRecord value9(Long value) {
        setVehiculosVendidos(value);
        return this;
    }

    @Override
    public VistaAnalisisFinancieroMensualRecord value10(Long value) {
        setRepuestosVendidos(value);
        return this;
    }

    @Override
    public VistaAnalisisFinancieroMensualRecord value11(BigDecimal value) {
        setPromedioVenta(value);
        return this;
    }

    @Override
    public VistaAnalisisFinancieroMensualRecord value12(BigDecimal value) {
        setRatioIngresosEgresos(value);
        return this;
    }

    @Override
    public VistaAnalisisFinancieroMensualRecord values(Integer value1, Integer value2, String value3, Long value4, BigDecimal value5, BigDecimal value6, BigDecimal value7, BigDecimal value8, Long value9, Long value10, BigDecimal value11, BigDecimal value12) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        value10(value10);
        value11(value11);
        value12(value12);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached VistaAnalisisFinancieroMensualRecord
     */
    public VistaAnalisisFinancieroMensualRecord() {
        super(VistaAnalisisFinancieroMensual.VISTA_ANALISIS_FINANCIERO_MENSUAL);
    }

    /**
     * Create a detached, initialised VistaAnalisisFinancieroMensualRecord
     */
    public VistaAnalisisFinancieroMensualRecord(Integer anio, Integer mes, String nombreMes, Long totalTransacciones, BigDecimal totalIngresos, BigDecimal totalEgresos, BigDecimal balanceNeto, BigDecimal totalComisiones, Long vehiculosVendidos, Long repuestosVendidos, BigDecimal promedioVenta, BigDecimal ratioIngresosEgresos) {
        super(VistaAnalisisFinancieroMensual.VISTA_ANALISIS_FINANCIERO_MENSUAL);

        setAnio(anio);
        setMes(mes);
        setNombreMes(nombreMes);
        setTotalTransacciones(totalTransacciones);
        setTotalIngresos(totalIngresos);
        setTotalEgresos(totalEgresos);
        setBalanceNeto(balanceNeto);
        setTotalComisiones(totalComisiones);
        setVehiculosVendidos(vehiculosVendidos);
        setRepuestosVendidos(repuestosVendidos);
        setPromedioVenta(promedioVenta);
        setRatioIngresosEgresos(ratioIngresosEgresos);
        resetChangedOnNotNull();
    }

    /**
     * Create a detached, initialised VistaAnalisisFinancieroMensualRecord
     */
    public VistaAnalisisFinancieroMensualRecord(com.rodiejacontable.database.jooq.tables.pojos.VistaAnalisisFinancieroMensual value) {
        super(VistaAnalisisFinancieroMensual.VISTA_ANALISIS_FINANCIERO_MENSUAL);

        if (value != null) {
            setAnio(value.getAnio());
            setMes(value.getMes());
            setNombreMes(value.getNombreMes());
            setTotalTransacciones(value.getTotalTransacciones());
            setTotalIngresos(value.getTotalIngresos());
            setTotalEgresos(value.getTotalEgresos());
            setBalanceNeto(value.getBalanceNeto());
            setTotalComisiones(value.getTotalComisiones());
            setVehiculosVendidos(value.getVehiculosVendidos());
            setRepuestosVendidos(value.getRepuestosVendidos());
            setPromedioVenta(value.getPromedioVenta());
            setRatioIngresosEgresos(value.getRatioIngresosEgresos());
            resetChangedOnNotNull();
        }
    }
}
