/*
 * This file is generated by jOOQ.
 */
package com.RodiejaContable.database.jooq.enums;


import org.jooq.Catalog;
import org.jooq.EnumType;
import org.jooq.Schema;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public enum InventarioRepuestosZona implements EnumType {

    _0_("0-"),

    Z1_("Z1-"),

    Z2_("Z2-"),

    Z3_("Z3-"),

    Z4_("Z4-"),

    Z5_("Z5-"),

    Z6_("Z6-");

    private final String literal;

    private InventarioRepuestosZona(String literal) {
        this.literal = literal;
    }

    @Override
    public Catalog getCatalog() {
        return null;
    }

    @Override
    public Schema getSchema() {
        return null;
    }

    @Override
    public String getName() {
        return null;
    }

    @Override
    public String getLiteral() {
        return literal;
    }

    /**
     * Lookup a value of this EnumType by its literal. Returns
     * <code>null</code>, if no such value could be found, see {@link
     * EnumType#lookupLiteral(Class, String)}.
     */
    public static InventarioRepuestosZona lookupLiteral(String literal) {
        return EnumType.lookupLiteral(InventarioRepuestosZona.class, literal);
    }
}
