/*
 * This file is generated by jOOQ.
 */
package com.rodiejacontable.database.jooq;


import com.rodiejacontable.database.jooq.routines.SpActividadAuditoriaFecha;
import com.rodiejacontable.database.jooq.routines.SpHistorialVehiculo;

import java.time.LocalDate;

import org.jooq.Configuration;


/**
 * Convenience access to all stored procedures and functions in
 * sistema_vehicular.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Routines {

    /**
     * Call <code>sistema_vehicular.sp_actividad_auditoria_fecha</code>
     */
    public static void spActividadAuditoriaFecha(
          Configuration configuration
        , LocalDate pFechaInicio
        , LocalDate pFechaFin
    ) {
        SpActividadAuditoriaFecha p = new SpActividadAuditoriaFecha();
        p.setPFechaInicio(pFechaInicio);
        p.setPFechaFin(pFechaFin);

        p.execute(configuration);
    }

    /**
     * Call <code>sistema_vehicular.sp_historial_vehiculo</code>
     */
    public static void spHistorialVehiculo(
          Configuration configuration
        , Integer pVehiculoId
    ) {
        SpHistorialVehiculo p = new SpHistorialVehiculo();
        p.setPVehiculoId(pVehiculoId);

        p.execute(configuration);
    }
}
