/*
 * This file is generated by jOOQ.
 */
package com.RodiejaContable.database.jooq.tables.pojos;


import com.RodiejaContable.database.jooq.enums.VistaVehiculosCompletaEstado;

import java.io.Serializable;
import java.math.BigDecimal;
import java.time.LocalDate;


/**
 * VIEW
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class VistaVehiculosCompleta implements Serializable {

    private static final long serialVersionUID = 1L;

    private Integer id;
    private String codigoVehiculo;
    private Integer anio;
    private BigDecimal precioCompra;
    private BigDecimal costoGrua;
    private BigDecimal comisiones;
    private BigDecimal inversionTotal;
    private BigDecimal precioVenta;
    private LocalDate fechaIngreso;
    private LocalDate fechaVenta;
    private VistaVehiculosCompletaEstado estado;
    private Byte activo;
    private String notas;
    private String marca;
    private String modelo;
    private String generacion;
    private String generacionDescripcion;
    private Integer anioInicio;
    private Integer anioFin;
    private String claveGeneracion;
    private BigDecimal totalIngresosVehiculo;
    private BigDecimal totalEgresosVehiculo;
    private BigDecimal balanceNetoVehiculo;

    public VistaVehiculosCompleta() {}

    public VistaVehiculosCompleta(VistaVehiculosCompleta value) {
        this.id = value.id;
        this.codigoVehiculo = value.codigoVehiculo;
        this.anio = value.anio;
        this.precioCompra = value.precioCompra;
        this.costoGrua = value.costoGrua;
        this.comisiones = value.comisiones;
        this.inversionTotal = value.inversionTotal;
        this.precioVenta = value.precioVenta;
        this.fechaIngreso = value.fechaIngreso;
        this.fechaVenta = value.fechaVenta;
        this.estado = value.estado;
        this.activo = value.activo;
        this.notas = value.notas;
        this.marca = value.marca;
        this.modelo = value.modelo;
        this.generacion = value.generacion;
        this.generacionDescripcion = value.generacionDescripcion;
        this.anioInicio = value.anioInicio;
        this.anioFin = value.anioFin;
        this.claveGeneracion = value.claveGeneracion;
        this.totalIngresosVehiculo = value.totalIngresosVehiculo;
        this.totalEgresosVehiculo = value.totalEgresosVehiculo;
        this.balanceNetoVehiculo = value.balanceNetoVehiculo;
    }

    public VistaVehiculosCompleta(
        Integer id,
        String codigoVehiculo,
        Integer anio,
        BigDecimal precioCompra,
        BigDecimal costoGrua,
        BigDecimal comisiones,
        BigDecimal inversionTotal,
        BigDecimal precioVenta,
        LocalDate fechaIngreso,
        LocalDate fechaVenta,
        VistaVehiculosCompletaEstado estado,
        Byte activo,
        String notas,
        String marca,
        String modelo,
        String generacion,
        String generacionDescripcion,
        Integer anioInicio,
        Integer anioFin,
        String claveGeneracion,
        BigDecimal totalIngresosVehiculo,
        BigDecimal totalEgresosVehiculo,
        BigDecimal balanceNetoVehiculo
    ) {
        this.id = id;
        this.codigoVehiculo = codigoVehiculo;
        this.anio = anio;
        this.precioCompra = precioCompra;
        this.costoGrua = costoGrua;
        this.comisiones = comisiones;
        this.inversionTotal = inversionTotal;
        this.precioVenta = precioVenta;
        this.fechaIngreso = fechaIngreso;
        this.fechaVenta = fechaVenta;
        this.estado = estado;
        this.activo = activo;
        this.notas = notas;
        this.marca = marca;
        this.modelo = modelo;
        this.generacion = generacion;
        this.generacionDescripcion = generacionDescripcion;
        this.anioInicio = anioInicio;
        this.anioFin = anioFin;
        this.claveGeneracion = claveGeneracion;
        this.totalIngresosVehiculo = totalIngresosVehiculo;
        this.totalEgresosVehiculo = totalEgresosVehiculo;
        this.balanceNetoVehiculo = balanceNetoVehiculo;
    }

    /**
     * Getter for <code>sistema_vehicular.vista_vehiculos_completa.id</code>.
     */
    public Integer getId() {
        return this.id;
    }

    /**
     * Setter for <code>sistema_vehicular.vista_vehiculos_completa.id</code>.
     */
    public VistaVehiculosCompleta setId(Integer id) {
        this.id = id;
        return this;
    }

    /**
     * Getter for
     * <code>sistema_vehicular.vista_vehiculos_completa.codigo_vehiculo</code>.
     */
    public String getCodigoVehiculo() {
        return this.codigoVehiculo;
    }

    /**
     * Setter for
     * <code>sistema_vehicular.vista_vehiculos_completa.codigo_vehiculo</code>.
     */
    public VistaVehiculosCompleta setCodigoVehiculo(String codigoVehiculo) {
        this.codigoVehiculo = codigoVehiculo;
        return this;
    }

    /**
     * Getter for <code>sistema_vehicular.vista_vehiculos_completa.anio</code>.
     */
    public Integer getAnio() {
        return this.anio;
    }

    /**
     * Setter for <code>sistema_vehicular.vista_vehiculos_completa.anio</code>.
     */
    public VistaVehiculosCompleta setAnio(Integer anio) {
        this.anio = anio;
        return this;
    }

    /**
     * Getter for
     * <code>sistema_vehicular.vista_vehiculos_completa.precio_compra</code>.
     */
    public BigDecimal getPrecioCompra() {
        return this.precioCompra;
    }

    /**
     * Setter for
     * <code>sistema_vehicular.vista_vehiculos_completa.precio_compra</code>.
     */
    public VistaVehiculosCompleta setPrecioCompra(BigDecimal precioCompra) {
        this.precioCompra = precioCompra;
        return this;
    }

    /**
     * Getter for
     * <code>sistema_vehicular.vista_vehiculos_completa.costo_grua</code>.
     */
    public BigDecimal getCostoGrua() {
        return this.costoGrua;
    }

    /**
     * Setter for
     * <code>sistema_vehicular.vista_vehiculos_completa.costo_grua</code>.
     */
    public VistaVehiculosCompleta setCostoGrua(BigDecimal costoGrua) {
        this.costoGrua = costoGrua;
        return this;
    }

    /**
     * Getter for
     * <code>sistema_vehicular.vista_vehiculos_completa.comisiones</code>.
     */
    public BigDecimal getComisiones() {
        return this.comisiones;
    }

    /**
     * Setter for
     * <code>sistema_vehicular.vista_vehiculos_completa.comisiones</code>.
     */
    public VistaVehiculosCompleta setComisiones(BigDecimal comisiones) {
        this.comisiones = comisiones;
        return this;
    }

    /**
     * Getter for
     * <code>sistema_vehicular.vista_vehiculos_completa.inversion_total</code>.
     */
    public BigDecimal getInversionTotal() {
        return this.inversionTotal;
    }

    /**
     * Setter for
     * <code>sistema_vehicular.vista_vehiculos_completa.inversion_total</code>.
     */
    public VistaVehiculosCompleta setInversionTotal(BigDecimal inversionTotal) {
        this.inversionTotal = inversionTotal;
        return this;
    }

    /**
     * Getter for
     * <code>sistema_vehicular.vista_vehiculos_completa.precio_venta</code>.
     */
    public BigDecimal getPrecioVenta() {
        return this.precioVenta;
    }

    /**
     * Setter for
     * <code>sistema_vehicular.vista_vehiculos_completa.precio_venta</code>.
     */
    public VistaVehiculosCompleta setPrecioVenta(BigDecimal precioVenta) {
        this.precioVenta = precioVenta;
        return this;
    }

    /**
     * Getter for
     * <code>sistema_vehicular.vista_vehiculos_completa.fecha_ingreso</code>.
     */
    public LocalDate getFechaIngreso() {
        return this.fechaIngreso;
    }

    /**
     * Setter for
     * <code>sistema_vehicular.vista_vehiculos_completa.fecha_ingreso</code>.
     */
    public VistaVehiculosCompleta setFechaIngreso(LocalDate fechaIngreso) {
        this.fechaIngreso = fechaIngreso;
        return this;
    }

    /**
     * Getter for
     * <code>sistema_vehicular.vista_vehiculos_completa.fecha_venta</code>.
     */
    public LocalDate getFechaVenta() {
        return this.fechaVenta;
    }

    /**
     * Setter for
     * <code>sistema_vehicular.vista_vehiculos_completa.fecha_venta</code>.
     */
    public VistaVehiculosCompleta setFechaVenta(LocalDate fechaVenta) {
        this.fechaVenta = fechaVenta;
        return this;
    }

    /**
     * Getter for
     * <code>sistema_vehicular.vista_vehiculos_completa.estado</code>.
     */
    public VistaVehiculosCompletaEstado getEstado() {
        return this.estado;
    }

    /**
     * Setter for
     * <code>sistema_vehicular.vista_vehiculos_completa.estado</code>.
     */
    public VistaVehiculosCompleta setEstado(VistaVehiculosCompletaEstado estado) {
        this.estado = estado;
        return this;
    }

    /**
     * Getter for
     * <code>sistema_vehicular.vista_vehiculos_completa.activo</code>.
     */
    public Byte getActivo() {
        return this.activo;
    }

    /**
     * Setter for
     * <code>sistema_vehicular.vista_vehiculos_completa.activo</code>.
     */
    public VistaVehiculosCompleta setActivo(Byte activo) {
        this.activo = activo;
        return this;
    }

    /**
     * Getter for <code>sistema_vehicular.vista_vehiculos_completa.notas</code>.
     */
    public String getNotas() {
        return this.notas;
    }

    /**
     * Setter for <code>sistema_vehicular.vista_vehiculos_completa.notas</code>.
     */
    public VistaVehiculosCompleta setNotas(String notas) {
        this.notas = notas;
        return this;
    }

    /**
     * Getter for <code>sistema_vehicular.vista_vehiculos_completa.marca</code>.
     */
    public String getMarca() {
        return this.marca;
    }

    /**
     * Setter for <code>sistema_vehicular.vista_vehiculos_completa.marca</code>.
     */
    public VistaVehiculosCompleta setMarca(String marca) {
        this.marca = marca;
        return this;
    }

    /**
     * Getter for
     * <code>sistema_vehicular.vista_vehiculos_completa.modelo</code>.
     */
    public String getModelo() {
        return this.modelo;
    }

    /**
     * Setter for
     * <code>sistema_vehicular.vista_vehiculos_completa.modelo</code>.
     */
    public VistaVehiculosCompleta setModelo(String modelo) {
        this.modelo = modelo;
        return this;
    }

    /**
     * Getter for
     * <code>sistema_vehicular.vista_vehiculos_completa.generacion</code>.
     */
    public String getGeneracion() {
        return this.generacion;
    }

    /**
     * Setter for
     * <code>sistema_vehicular.vista_vehiculos_completa.generacion</code>.
     */
    public VistaVehiculosCompleta setGeneracion(String generacion) {
        this.generacion = generacion;
        return this;
    }

    /**
     * Getter for
     * <code>sistema_vehicular.vista_vehiculos_completa.generacion_descripcion</code>.
     */
    public String getGeneracionDescripcion() {
        return this.generacionDescripcion;
    }

    /**
     * Setter for
     * <code>sistema_vehicular.vista_vehiculos_completa.generacion_descripcion</code>.
     */
    public VistaVehiculosCompleta setGeneracionDescripcion(String generacionDescripcion) {
        this.generacionDescripcion = generacionDescripcion;
        return this;
    }

    /**
     * Getter for
     * <code>sistema_vehicular.vista_vehiculos_completa.anio_inicio</code>.
     */
    public Integer getAnioInicio() {
        return this.anioInicio;
    }

    /**
     * Setter for
     * <code>sistema_vehicular.vista_vehiculos_completa.anio_inicio</code>.
     */
    public VistaVehiculosCompleta setAnioInicio(Integer anioInicio) {
        this.anioInicio = anioInicio;
        return this;
    }

    /**
     * Getter for
     * <code>sistema_vehicular.vista_vehiculos_completa.anio_fin</code>.
     */
    public Integer getAnioFin() {
        return this.anioFin;
    }

    /**
     * Setter for
     * <code>sistema_vehicular.vista_vehiculos_completa.anio_fin</code>.
     */
    public VistaVehiculosCompleta setAnioFin(Integer anioFin) {
        this.anioFin = anioFin;
        return this;
    }

    /**
     * Getter for
     * <code>sistema_vehicular.vista_vehiculos_completa.clave_generacion</code>.
     */
    public String getClaveGeneracion() {
        return this.claveGeneracion;
    }

    /**
     * Setter for
     * <code>sistema_vehicular.vista_vehiculos_completa.clave_generacion</code>.
     */
    public VistaVehiculosCompleta setClaveGeneracion(String claveGeneracion) {
        this.claveGeneracion = claveGeneracion;
        return this;
    }

    /**
     * Getter for
     * <code>sistema_vehicular.vista_vehiculos_completa.total_ingresos_vehiculo</code>.
     */
    public BigDecimal getTotalIngresosVehiculo() {
        return this.totalIngresosVehiculo;
    }

    /**
     * Setter for
     * <code>sistema_vehicular.vista_vehiculos_completa.total_ingresos_vehiculo</code>.
     */
    public VistaVehiculosCompleta setTotalIngresosVehiculo(BigDecimal totalIngresosVehiculo) {
        this.totalIngresosVehiculo = totalIngresosVehiculo;
        return this;
    }

    /**
     * Getter for
     * <code>sistema_vehicular.vista_vehiculos_completa.total_egresos_vehiculo</code>.
     */
    public BigDecimal getTotalEgresosVehiculo() {
        return this.totalEgresosVehiculo;
    }

    /**
     * Setter for
     * <code>sistema_vehicular.vista_vehiculos_completa.total_egresos_vehiculo</code>.
     */
    public VistaVehiculosCompleta setTotalEgresosVehiculo(BigDecimal totalEgresosVehiculo) {
        this.totalEgresosVehiculo = totalEgresosVehiculo;
        return this;
    }

    /**
     * Getter for
     * <code>sistema_vehicular.vista_vehiculos_completa.balance_neto_vehiculo</code>.
     */
    public BigDecimal getBalanceNetoVehiculo() {
        return this.balanceNetoVehiculo;
    }

    /**
     * Setter for
     * <code>sistema_vehicular.vista_vehiculos_completa.balance_neto_vehiculo</code>.
     */
    public VistaVehiculosCompleta setBalanceNetoVehiculo(BigDecimal balanceNetoVehiculo) {
        this.balanceNetoVehiculo = balanceNetoVehiculo;
        return this;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        final VistaVehiculosCompleta other = (VistaVehiculosCompleta) obj;
        if (this.id == null) {
            if (other.id != null)
                return false;
        }
        else if (!this.id.equals(other.id))
            return false;
        if (this.codigoVehiculo == null) {
            if (other.codigoVehiculo != null)
                return false;
        }
        else if (!this.codigoVehiculo.equals(other.codigoVehiculo))
            return false;
        if (this.anio == null) {
            if (other.anio != null)
                return false;
        }
        else if (!this.anio.equals(other.anio))
            return false;
        if (this.precioCompra == null) {
            if (other.precioCompra != null)
                return false;
        }
        else if (!this.precioCompra.equals(other.precioCompra))
            return false;
        if (this.costoGrua == null) {
            if (other.costoGrua != null)
                return false;
        }
        else if (!this.costoGrua.equals(other.costoGrua))
            return false;
        if (this.comisiones == null) {
            if (other.comisiones != null)
                return false;
        }
        else if (!this.comisiones.equals(other.comisiones))
            return false;
        if (this.inversionTotal == null) {
            if (other.inversionTotal != null)
                return false;
        }
        else if (!this.inversionTotal.equals(other.inversionTotal))
            return false;
        if (this.precioVenta == null) {
            if (other.precioVenta != null)
                return false;
        }
        else if (!this.precioVenta.equals(other.precioVenta))
            return false;
        if (this.fechaIngreso == null) {
            if (other.fechaIngreso != null)
                return false;
        }
        else if (!this.fechaIngreso.equals(other.fechaIngreso))
            return false;
        if (this.fechaVenta == null) {
            if (other.fechaVenta != null)
                return false;
        }
        else if (!this.fechaVenta.equals(other.fechaVenta))
            return false;
        if (this.estado == null) {
            if (other.estado != null)
                return false;
        }
        else if (!this.estado.equals(other.estado))
            return false;
        if (this.activo == null) {
            if (other.activo != null)
                return false;
        }
        else if (!this.activo.equals(other.activo))
            return false;
        if (this.notas == null) {
            if (other.notas != null)
                return false;
        }
        else if (!this.notas.equals(other.notas))
            return false;
        if (this.marca == null) {
            if (other.marca != null)
                return false;
        }
        else if (!this.marca.equals(other.marca))
            return false;
        if (this.modelo == null) {
            if (other.modelo != null)
                return false;
        }
        else if (!this.modelo.equals(other.modelo))
            return false;
        if (this.generacion == null) {
            if (other.generacion != null)
                return false;
        }
        else if (!this.generacion.equals(other.generacion))
            return false;
        if (this.generacionDescripcion == null) {
            if (other.generacionDescripcion != null)
                return false;
        }
        else if (!this.generacionDescripcion.equals(other.generacionDescripcion))
            return false;
        if (this.anioInicio == null) {
            if (other.anioInicio != null)
                return false;
        }
        else if (!this.anioInicio.equals(other.anioInicio))
            return false;
        if (this.anioFin == null) {
            if (other.anioFin != null)
                return false;
        }
        else if (!this.anioFin.equals(other.anioFin))
            return false;
        if (this.claveGeneracion == null) {
            if (other.claveGeneracion != null)
                return false;
        }
        else if (!this.claveGeneracion.equals(other.claveGeneracion))
            return false;
        if (this.totalIngresosVehiculo == null) {
            if (other.totalIngresosVehiculo != null)
                return false;
        }
        else if (!this.totalIngresosVehiculo.equals(other.totalIngresosVehiculo))
            return false;
        if (this.totalEgresosVehiculo == null) {
            if (other.totalEgresosVehiculo != null)
                return false;
        }
        else if (!this.totalEgresosVehiculo.equals(other.totalEgresosVehiculo))
            return false;
        if (this.balanceNetoVehiculo == null) {
            if (other.balanceNetoVehiculo != null)
                return false;
        }
        else if (!this.balanceNetoVehiculo.equals(other.balanceNetoVehiculo))
            return false;
        return true;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((this.id == null) ? 0 : this.id.hashCode());
        result = prime * result + ((this.codigoVehiculo == null) ? 0 : this.codigoVehiculo.hashCode());
        result = prime * result + ((this.anio == null) ? 0 : this.anio.hashCode());
        result = prime * result + ((this.precioCompra == null) ? 0 : this.precioCompra.hashCode());
        result = prime * result + ((this.costoGrua == null) ? 0 : this.costoGrua.hashCode());
        result = prime * result + ((this.comisiones == null) ? 0 : this.comisiones.hashCode());
        result = prime * result + ((this.inversionTotal == null) ? 0 : this.inversionTotal.hashCode());
        result = prime * result + ((this.precioVenta == null) ? 0 : this.precioVenta.hashCode());
        result = prime * result + ((this.fechaIngreso == null) ? 0 : this.fechaIngreso.hashCode());
        result = prime * result + ((this.fechaVenta == null) ? 0 : this.fechaVenta.hashCode());
        result = prime * result + ((this.estado == null) ? 0 : this.estado.hashCode());
        result = prime * result + ((this.activo == null) ? 0 : this.activo.hashCode());
        result = prime * result + ((this.notas == null) ? 0 : this.notas.hashCode());
        result = prime * result + ((this.marca == null) ? 0 : this.marca.hashCode());
        result = prime * result + ((this.modelo == null) ? 0 : this.modelo.hashCode());
        result = prime * result + ((this.generacion == null) ? 0 : this.generacion.hashCode());
        result = prime * result + ((this.generacionDescripcion == null) ? 0 : this.generacionDescripcion.hashCode());
        result = prime * result + ((this.anioInicio == null) ? 0 : this.anioInicio.hashCode());
        result = prime * result + ((this.anioFin == null) ? 0 : this.anioFin.hashCode());
        result = prime * result + ((this.claveGeneracion == null) ? 0 : this.claveGeneracion.hashCode());
        result = prime * result + ((this.totalIngresosVehiculo == null) ? 0 : this.totalIngresosVehiculo.hashCode());
        result = prime * result + ((this.totalEgresosVehiculo == null) ? 0 : this.totalEgresosVehiculo.hashCode());
        result = prime * result + ((this.balanceNetoVehiculo == null) ? 0 : this.balanceNetoVehiculo.hashCode());
        return result;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("VistaVehiculosCompleta (");

        sb.append(id);
        sb.append(", ").append(codigoVehiculo);
        sb.append(", ").append(anio);
        sb.append(", ").append(precioCompra);
        sb.append(", ").append(costoGrua);
        sb.append(", ").append(comisiones);
        sb.append(", ").append(inversionTotal);
        sb.append(", ").append(precioVenta);
        sb.append(", ").append(fechaIngreso);
        sb.append(", ").append(fechaVenta);
        sb.append(", ").append(estado);
        sb.append(", ").append(activo);
        sb.append(", ").append(notas);
        sb.append(", ").append(marca);
        sb.append(", ").append(modelo);
        sb.append(", ").append(generacion);
        sb.append(", ").append(generacionDescripcion);
        sb.append(", ").append(anioInicio);
        sb.append(", ").append(anioFin);
        sb.append(", ").append(claveGeneracion);
        sb.append(", ").append(totalIngresosVehiculo);
        sb.append(", ").append(totalEgresosVehiculo);
        sb.append(", ").append(balanceNetoVehiculo);

        sb.append(")");
        return sb.toString();
    }
}
